### ISSUE TITLE
Add support for query string expression

### ISSUE THREAD

**Issue by karldahlgren** [castlemock/castlemock#101]
Add support to extract request query strings and apply them to the mocked response, similar to the path parameter expression.

The new expression will be called query string and function the same as path parameter expression.

Example
URL: /test?query=Hello
Expression: ${QUERY_STRING(query="query")}
Result: Hello

**Comment by karldahlgren** [comment]
This feature has been implemented

**Comment by mhewedy** [comment]
I didn't get the idea behind this issue. the whole ANTLR module is a black box to me. can you give a quick idea about how this part is used in the context of castle mock?

**Comment by karldahlgren** [comment]
Thank you so much @kyleshrader for point this out.
I have now added it to the documentation.

Best regards,
Karl Dahlgren
