### ISSUE TITLE
Mocked SOAP operation requesting access to real endpoint

### ISSUE THREAD

**Issue by Honatas** [castlemock/castlemock#103]
I have created a new SOAP project and imported the WSDL file. I have no access to the real endpoint of this service from my machine. I have created a response for one of the operations. The status of the operation is "Mocked". When I try to make a request to this mocked operation, Castlemock either tries to access or redirects to the real endpoint and fails. My java client throws an java.net.UnknownHostException: <real_endpoint>. Tested on versions 1.29 and 1.33.

**Comment by karldahlgren** [comment]
Hi @Honatas.
That seems very odd. How do you call the SOAP service? Does your software retrieve the WSDL file from Castle Mock? Please note that Castle Mock will not alter the WSDL file in any way. This means that if the WSDL file is referring to the original host, your software might extract that URL and use that instead. In those cases you need to specifically override the WSDL endpoint URL in your code.
 
Would it be possible for you to send me the exported project?
You can send it to me directly on karl.dahlgren@castlemock.com.

Thank you very much!
Best regards,
Karl Dahlgren

**Comment by Honatas** [comment]
The WSDL contained the real endpoint URL. Overriding it in my code was not enough. To make this work I had to do the following:

1 - Create a new Castlemock project
2- Check the created project url to get the project ID
3- Build the new endpoint URL using the project ID and modify it in the WSDL
4- Upload the modified WSDL to the Castlemock project

This is not a Castlemock issue. Anyway, I'd suggest to display the project ID in the project page.

Thanks and sorry for the trouble.
