### ISSUE TITLE
XPath (or similar) response strategy for REST

### ISSUE THREAD

**Issue by karldahlgren** [castlemock/castlemock#107]
Add support for XPath (Or something similar) response strategy for REST. See issue #63 for further information.

**Comment by mhewedy** [comment]
JSON Path might work with JSON-based reset services.

**Comment by CamiloCode** [comment]
thanks for creating the ticket @karldahlgren

**Comment by tiagoguimaraesss** [comment]
Hello guys,

This improvement is very useful. When working with Rest Services, it is very common to have something like:

**POST myrestapi/doLogin**
Payload:
`{
      "username": "tiagoguimaraesss",
      "password": "123456"
}`

Castle Mock currently does not support this type of operation. 

Best regards!

**Comment by karldahlgren** [comment]
Added support for both XPath and JSON Path. This will be part of the next release.

Best regards,
Karl Dahlgren
