### ISSUE TITLE
Allow bypass SSL Handshake

### ISSUE THREAD

**Issue by mhewedy** [castlemock/castlemock#114]
**Is your feature request related to a problem? Please describe.**
Yes, one of my college try to mock service with invalid https certificate

**Describe the solution you'd like**
Add some option (cli startup option for sake of simplcity) to allow this

**Describe alternatives you've considered**
import the SSL certificate in castlemock java's keychain ... Ouch very boring 😞 

What do you think Karl?

**Comment by karldahlgren** [comment]
Hi @mhewedy.
I haven't mocked a service with an invalid https certificate, but I can imagine that Java's default behavior is to fail upon this. I agree that it would be nice to add this as a feature option. The current workaround is to simply add the certificate to their Java keychain.

Have you thought about any solution for how to disable the certificate check?

Once again, great idea!
Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
Yes.. and I have it ready... I will send PR soon, please review it and let's discuss about it.

**Comment by karldahlgren** [comment]
Excellent! Looking forward to see it 😄

**Comment by karldahlgren** [comment]
The feature is now part of Castle Mock 1.36 which has now been released and is available on https://castlemock.com and Docker.

**Comment by mhewedy** [comment]
Thank you very much @karldahlgren , much appreciated 😄 👍
