### ISSUE TITLE
Query parameters with underscores not being resolved in expressions

### ISSUE THREAD

**Issue by ideonvanniekerk** [castlemock/castlemock#116]
**Describe the bug**
Query parameters with underscores not being resolved in expressions.

**To Reproduce**
1. Setup a sample REST project 
2. In response configure it to print out path param with underscore like ${QUERY_STRING(query="user_name")}
3. Invoke url with path parameter like test?user_name=Ideon
4. See how response does not print out parameter

**Expected behavior**
Response should resolve the path expression parameter and print it with the response.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version * docker image castlemock/castlemock:1.35

**Additional context**
Not sure if there is a special expression to be used with underscores. Was unable to find anything in the documentation.

**Comment by karldahlgren** [comment]
Hi @ideonvanniekerk.
Thank you for reporting this issue. I've been able to reproduce the issue and hopefully it should be easy to resolve. I will work on a fix during the weekend and do a new release at the same time.

Once again, thank you very much.
Best regards,
Karl Dahlgren

**Comment by ideonvanniekerk** [comment]
Awesome, thanks.

Looking forward to it being fixed.

**Comment by karldahlgren** [comment]
This issue has now been resolved and will be part of the next release.
Thank you once again for reporting this.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
The fix is part of the latest release that was just released. It is available on Github, our webpage and on Docker.

Best regards,
Karl Dahlgren

**Comment by ideonvanniekerk** [comment]
That is great, thanks @karldahlgren that is good news. I am sure to test this out today.

A+++ for castlemock as a mocking tool!

**Comment by karldahlgren** [comment]
Great to hear @ideonvanniekerk!
Don't hesitate to report other bugs or request features or improvements. All feedback is very much appreciated 😄 

Best regards,
Karl Dahlgren
