### ISSUE TITLE
Resource bulk update does not work

### ISSUE THREAD

**Issue by saiello** [castlemock/castlemock#120]
**Describe the bug**
Bulk update does not work properly

**To Reproduce**
1. Go to 'Project > Application'
2. Check some resources
3. Change select ( ie. From Mocked to Disabled )
3. Click on 'Update'
4. All resources will be update

**Expected behavior**
Only checked resource should be updated

**Comment by karldahlgren** [comment]
Hi @saiello.
Thank you for the bug report. I will take a look at it as soon as I can 😄 
Should be an easy fix. If so, then I can prepare a new release right away.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
This bug has been resolved and will be part of next release.

Best regards,
Karl Dahlgren
