### ISSUE TITLE
Expressions in REST project not working v 1.37

### ISSUE THREAD

**Issue by jorgeagarzone** [castlemock/castlemock#130]
**Describe the bug**
According https://castlemock.com/expressions/ I can use expressions in REST projects, but is not working in docker version 1.37

**To Reproduce**
1. Pull docker image 1.37
`docker pull castlemock/castlemock:1.37`
`docker run -d -p 9000:8080 -v $(pwd):/root/.castlemock --name castlemock castlemock/castlemock:1.37`
2. Create rest project, application, resource and GET method
3. Add following body to a new response:
{
	"test": "test",
	"abc": ${RANDOM_BOOLEAN()}
}
4. Call the REST service and see response:
{
	"test": "test",
	"abc": ${RANDOM_BOOLEAN()}
}

**Expected behavior**
abc should be a random boolean.

**Screenshots**
<img width="1448" alt="Captura de Pantalla 2019-06-07 a la(s) 9 42 16 a  m" src="https://user-images.githubusercontent.com/48358363/59113131-19615c00-890a-11e9-87c9-291806e53b7c.png">
<img width="1414" alt="Captura de Pantalla 2019-06-07 a la(s) 9 42 08 a  m" src="https://user-images.githubusercontent.com/48358363/59113139-1d8d7980-890a-11e9-84a8-675e4eca4f16.png">

**Desktop (please complete the following information):**
 - OS: mac - docker 
 - Browser n/a
 - Version docker image 1.37

**Comment by karldahlgren** [comment]
Hi @jorgeagarzone.
I can see that you haven’t enabled expressions on the mock page. Check the checkbox “Use expressions”, save and try again. I hope it helps.

Best regards,
Karl Dahlgren

**Comment by jorgeagarzone** [comment]
I am just blind and had not seen the checkbox , jejejej thanks man.

**Comment by karldahlgren** [comment]
Haha, no problem.
Feel free to create another issue if you get blind again and need some support =)
Good luck!

Best regards,
Karl Dahlgren
