### ISSUE TITLE
unable to upload the wsdl :: error :: Unable to find operation output

### ISSUE THREAD

**Issue by ishwaryaAug** [castlemock/castlemock#132]
hi,
when i try to upload the wsdl file, i m getting below error 
"ERROR: com.castlemock.web.mock.soap.web.view.controller.project.SoapAddWSDLController - Exception: java.lang.IllegalArgumentException: Unable to find operation output"

it is valid wsdl file which is currently wrking.

kindly help on this

**Comment by ishwaryaAug** [comment]
problem with wsdl which i was using... after using corrected wsdl ,i can able to upload.
thanks anyway.

**Comment by karldahlgren** [comment]
Good to hear that you managed to resolve the issue @ishwaryaAug.
Don't hesitate to contact again if you have any further questions or problems.

Best regards,
Karl Dahlgren
