### ISSUE TITLE
Header and Query filed in query parameter , how to 

### ISSUE THREAD

**Issue by thulasipavankumar** [castlemock/castlemock#133]
This is more of a **help wanted** or guidance.I am playing around castlemock and my requirement is to send dynamic response based on query parameters,after stumbling upon I am unable to under stand difference between header and query fields in the method
![image](https://user-images.githubusercontent.com/3539745/60603078-57408b80-9db5-11e9-8bbd-6674d4be18ec.png)

P.S Thanks for the great project its makes life simpler :+1:

**Comment by karldahlgren** [comment]
Hi @thulasipavankumar.
My apologies for the late response. The header input field is specifying the name of the header, such as accept or content-type. The Query is just a simple input which the value of the incoming header needs to match.

Example:
Header: Content-Type
Query: application/json

If you check "Match Any", then the query will match any input.
If you check "Match Case", then the value is case sensitive.
"Match Regex" means that Castle Mock will try to parse the incoming header value with a regex. Example: Regex: a*b, Value aaaaab.

I hope this helps you.
Don't hesitate to contact again if you have any further questions.

Best regards,
Karl Dahlgren
