### ISSUE TITLE
Can't upload a SOAP

### ISSUE THREAD

**Issue by WilliamCSA04** [castlemock/castlemock#136]
Hello, I'm having a problem. 
I'm trying to use [this wsdl](http://webservices.society.net.br/139/operacoes/Society-ws-139-operacoes-jogos.WSDL) as a SOAP API.

![error](https://user-images.githubusercontent.com/12972870/63959186-ff936900-ca61-11e9-94e0-7a2fd7b45ed5.png)

- I created a project, then when into upload WSDL.
- Added [this wsdl](http://webservices.society.net.br/139/operacoes/Society-ws-139-operacoes-jogos.WSDL) there.

I have received an upload error on this. So I put that on a WSDL validator and was some things weird on it, so I try to adapt it until the validator found no error, but the upload error still occurs.

[xml.txt](https://github.com/castlemock/castlemock/files/3556555/xml.txt).

But my true issue is that the [SOAP](http://webservices.society.net.br/139/operacoes/Society-ws-139-operacoes-jogos.WSDL) I have linked does work because I can extract data from there. That is the WSDL that I use to get data from the production environment.

**Comment by karldahlgren** [comment]
Hi @WilliamCSA04.
My apologies for the late response. I have been looking into this issue and your WSDL. However, I haven't been able to locate or solve the problem yet. I will keep looking into the problem and keep you updated. Just wanted to inform you to let you know that I haven't forgotten or missed this issue 😄.

Best regards,
Karl Dahlgren

**Comment by anagori** [comment]
Hi @karldahlgren ,

I bumped into similar issue as well, is there any more finding to it.

Many Thanks !!
_________
Anurag

**Comment by dtorresgithub** [comment]
Hi @karldahlgren ,

I am getting the same error "Unable to upload or parse the file", I am wondering if it could be something tomcat is restricting or wsdl file is not supported? I have attached the wsdl file I am using.

Thanks & Regards
David Montes de Oca
[TransactionProcessing.zip](https://github.com/castlemock/castlemock/files/4652708/TransactionProcessing.zip)

**Comment by karldahlgren** [comment]
Hi @dtorresgithub.
I just tried to upload your WSDL file and it worked great. How are you uploading the WSDL? Are you uploading the WSDL or the zip file? Did you create a SOAP project? Which version are you using? There was a new version released yesterday. Have you tried it with the latest version?

<img width="1100" alt="136" src="https://user-images.githubusercontent.com/4678380/82370954-ad440f00-9a19-11ea-9291-9676c63006fb.png">

Thanks!
Best regards,
Karl Dahlgren

**Comment by dtorresgithub** [comment]
Hi @karldahlgren ,
Thanks for the quick response.
I uploaded the wsdl file (no zip). I created a SOAP project. Version is 1.48 (just set up this morning). This is running in Linux server tomcat.
From my side I am checking if there is some upload restrictions that might be causing this issue.

Thanks & Regards
David Montes de Oca

**Comment by dtorresgithub** [comment]
Hi @karldahlgren ,

Is now working, this was the fix sent by web person:

add /castlemock/ to HTTP header security filter in web.xml

Looks like this is on the server side.

Thanks & Regards
David Montes de Oca

**Comment by karldahlgren** [comment]
Great to hear @dtorresgithub!
Feel free to contact me if you are facing any other issues or have any questions.

Best regards,
Karl Dahlgren
