### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED gzip encoding

### ISSUE THREAD

**Issue by GrumpyMeow** [castlemock/castlemock#137]
Hi,

just trying out Castle-Mock. 
I noticed that Chrome gave errors about "ERR_CONTENT_DECODING_FAILED".
Apparently it has got something to do Content-Encoding repsonse header which was set to "GZIP", but Castle Mock was returning the response without compression. 
An OOTB solution would make the tool even better :-)

thank you for providing the tool.

**Comment by karldahlgren** [comment]
Hi @GrumpyMeow!
Thank you for using it and for raising this issue. I will look into to it tomorrow together with your other ticket. I really appreciate it you creating these ticket and bringing these issues to my attention. Helps making Castle Mock better. Thanks!

Best regards,
Karl Dahlgren

**Comment by GrumpyMeow** [comment]
I fixed it by making a small change in the file "AbstractRestServiceController.java".

The fix is simply omitting the "Content-Encoding" header from the response.

HttpHeaders responseHeaders = new HttpHeaders();
            for (HttpHeader httpHeader : response.getHttpHeaders()) {
                if (!httpHeader.getName().equalsIgnoreCase("Content-Encoding") ) {
                    List<String> headerValues = new LinkedList<String>();
                    headerValues.add(httpHeader.getValue());
                    responseHeaders.put(httpHeader.getName(), headerValues);
                }
            }

**Comment by karldahlgren** [comment]
Thank you so much for pointing this out @GrumpyMeow.
The issue should now have been resolved. Will be part of the next release (1.40).

Best regards,
Karl Dahlgren
