### ISSUE TITLE
Add network simulation delay

### ISSUE THREAD

**Issue by karldahlgren** [castlemock/castlemock#14]
Castle Mock projects should be able to be configured to simulated network delay.

**Comment by karldahlgren** [comment]
Added support for simulated network delay. It can be configured for each SOAP operation or each REST method.

**Comment by spartancr8** [comment]
Hi @karldahlgren:

Is there a way to make the network delay available for each mock, not the whole operation? I want to make request match on SOAP, but I want only specific mocks to show network delay. Right now, as long as I've seen, the network delay is applied to the whole operation.

Thank you in advance.

Regards,

**Comment by karldahlgren** [comment]
Hi @spartancr8.
My apologies for the delay. Unfortunately, it can only be done on an operation level, but it has crossed my mind to move that functionality to the mocked response itself (Or at least have it as an alternativ). Is this something that would help you?

Thank you!
Best regards,
Karl Dahlgren
