### ISSUE TITLE
Unable to parse request body when expression pints to single item

### ISSUE THREAD

**Issue by mbilinainteca** [castlemock/castlemock#140]
I've encountered an error while I was trying to use Body JSON Path feature.
When path expression points to a single item instead of multiple items, returned type is String and it cannot be cast to JSONArray.

Request body:
{
  "definite": "value"
}

Path expression:
$.definite

**Comment by miniyk2012** [comment]
i also found this bug

**Comment by karldahlgren** [comment]
Issue has been resolved and will be part of the next release (1.40)
