### ISSUE TITLE
Table "(Un-)select" all items (responses) in a table 

### ISSUE THREAD

**Issue by GrumpyMeow** [castlemock/castlemock#142]
Hi,

In case of many recorded responses it would make it easier to select & delete multiple items at one time.

**Comment by karldahlgren** [comment]
Hi @GrumpyMeow.
I like the idea! However, I'm trying to minimize the work being done on the current interface. The plan is to completely reproduce the current UI with a modern framework. In this process, I will do these kind of improvements.

I hope that I get time to implement the new UI as soon as possible.

Best regards,
Karl Dahlgren

**Comment by GrumpyMeow** [comment]
Hi Karl,

I completely understand that you make decisions to focus. I created this issue as a suggestion for improvement. No problem. I will close this issue.
