### ISSUE TITLE
Unable to identify REST method, if url parts are same for both GET and POST methods

### ISSUE THREAD

**Issue by tharishreddy** [castlemock/castlemock#143]
**Describe the bug**
If we have the following REST urls
GET /api/user/{id}
POST /api/user/search

Sometimes, it's generating the error **Unable to identify REST method** for POST methods

Looks like there is a bug in identifying rest method logic. 

Had a quick look into **IdentifyRestMethodService.java** which calls findRestResource (line 53), and it further uses UrlUtility.compareUri which results in returning either /api/user/{id} or /api/user/search without checking the httpMethod (GET/POST). If it returns the GET method instead of POST, subsequent logic checking whether the rest method http type is matched or not. (line 58), then it will fail.

compareUri("/user/{id}", "/user/search") returns true as expected.

Solution might be either return list of matched urls from findRestResource  and check for exact match further using httpMethodType. or pass httpMthodType to findRestResource itself and get  matched url (atmost one).

**Comment by karldahlgren** [comment]
Hi @tharishreddy 
My apologies for the late response. I started looking into this issue and I can confirm that you are absolutely right. I'm currently working on a solution. I will keep you posted.

Thank you very much for reporting this.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
This issue has been resolved and will be part of the next release, 1.40.

Best regards,
Karl Dahlgren
