### ISSUE TITLE
Tomcat/Debian Start Castle Mock

### ISSUE THREAD

**Issue by caed** [castlemock/castlemock#144]
Good Morning.

For help, we created a "debian" Linux server in the Azure cloud, installed either Java and Tomcat, ran or deployed castle simulations.

We are having a problem trying to start or mock castles.

**_FAIL - Application at context path [/castlemock] could not be started
FAIL - Encountered exception [org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[104.41.59.88].StandardContext[/castlemock]]]_**

When uploading the application on windows, there was no problem.

Could you support us in this mistake, what should we do?

Thanks.

**Comment by karldahlgren** [comment]
Hi @caed.
Of course I will support you as much as I can 😃.
Could you provide which Java version and Tomcat version you are using so that I can try to reproduce the issue?

Thank you very much!
Best regards,
Karl Dahlgren

**Comment by caed** [comment]
Oi @karldahlgren, obrigado pela ajuda.

Descobri a causa raiz do problema, quando for subir no linux, a pasta tomcat deverá estar com o user/group do tomcat, e não como root ou outro usuario. 

Após alterar o dono da pasta a aplicação funcionou.

Obrigado.

**Comment by caed** [comment]
Hi @karldahlgren, thanks for the help.

I found out the root cause of the problem, when going to linux, the tomcat folder should be with the tomcat user / group, not as root or another user.

After changing the folder owner the application worked.

Thank you very much!
Carlos Eduardo.

**Comment by karldahlgren** [comment]
Great to hear! Closing this issue.

Best regards,
Karl Dahlgren
