### ISSUE TITLE
Unable to extract the SOAP body

### ISSUE THREAD

**Issue by anagori** [castlemock/castlemock#155]
Dear Team, 

We mocked a SOAP HTTP 1.1 service over castle mock v1.39, We get below error in case I do not use the same namespace tag for body as the soap envelope. Any fix on same is highly appreciated.
 
**//error-response>
   error-message>Unable to extract the SOAP body</error-message
</error-response//**

**Requests work fine using :-**
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <**_soapenv:Body_** xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"> 

**Requests fail with error using :-** 
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <_**soap:Body**_ xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"> 

Regards,
Anurag

**Comment by anagori** [comment]
Anyone can help with this please... Or need more info...

**Comment by karldahlgren** [comment]
Hi @anagori.
Sorry for the late response here.
The reason why the second request is failing is that you are referring to "soap" in soap:Body. However, you have never declared the soap namespace in the second request. If you look at the first request you can see that you are referring to soapenv, which has been declared in the request.

I hope you find the helpful.
Best regards,
Karl Dahlgren

**Comment by anagori** [comment]
Thanks Karl... But I see that in second request as well the namespace has been declared implicit within the tag. And I tested same with SOAP UI mock it works good but not with Castle Mock. Can you help further.

<**soap**:Body **xmlns:soap**="http://schemas.xmlsoap.org/soap/envelope/">

**Comment by karldahlgren** [comment]
Hi @anagori.
You are absolutely right. My mistake. Sorry for missing it.
I was able to reproduce the issue and I have also managed to resolve it.
The fix will be part of the next release which will be released tomorrow.

Once again, thank you reporting this issue and my apologize for missing it.
Best regards,
Karl Dahlgren

**Comment by anagori** [comment]
Hi,

I pulled the latest version of castle mock, and I am still struggling with same issue :(
Can you please recheck or help me if i have to pull with some specific version.
________
Regards,
Anurag

**Comment by karldahlgren** [comment]
Hi @anagori.
Which version are you trying? Is it possible for you to provide a WSDL example that can reproduce this issue?

Thanks!
Best regards,
Karl Dahlgren

**Comment by anagori** [comment]
Hi @karldahlgren,

I am using version 1.39. I will share the request/response shortly.
__________
Regards,
Anurag

**Comment by karldahlgren** [comment]
Hi @anagori.
The latest version is 1.44 and your fix was part of 1.42. You should download and test the latest version.

Best regards,
Karl Dahlgren

**Comment by anagori** [comment]
I pulled the latest image from docker hub, somehow I got  again old 1.39.

Now, I pulled explicitly 1.42 and issue is resolved.

Thanks a lot for your very quick feedback 👍
