### ISSUE TITLE
We need Rest API to import project of type REST into castle mock 

### ISSUE THREAD

**Issue by praveenkumar466** [castlemock/castlemock#156]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by karldahlgren** [comment]
Hi @praveenkumar466.
The REST API already provides a service to import projects into Castle Mock. Please see the following service: http://localhost:8080/castlemock/swagger-ui.html#/Core/importProjectUsingPOST

Best regards,
Karl Dahlgren
