### ISSUE TITLE
"Update endpoint" does not respect checkboxes. Updates all forwarding endpoints.

### ISSUE THREAD

**Issue by GrumpyMeow** [castlemock/castlemock#173]
I'm using a somewhat older version of Castle Mock.
When i select a few "Resources" with checkboxes and choose the button "Update endpoint" i do see a correct list, but eventually all Endpoints are updated with the new endpoint-value.

I expected that only the selected resources would be updated.

The issue is still in the latest master-branch..
In this code:
```
    public ServiceResult<UpdateRestResourcesForwardedEndpointOutput> process(final ServiceTask<UpdateRestResourcesForwardedEndpointInput> serviceTask) {
        final UpdateRestResourcesForwardedEndpointInput input = serviceTask.getInput();
        final List<RestResource> resources = this.resourceRepository.findWithApplicationId(input.getRestApplicationId());
```

**Comment by karldahlgren** [comment]
This issue is now resolved and will be part of the next release, v1.47
Thank you once again for reporting this issue.

Best regards,
Karl Dahlgren
