### ISSUE TITLE
Import of Swagger 2.0 or OpenApi 3.0.0 files failed [v1.43]

### ISSUE THREAD

**Issue by 3logy** [castlemock/castlemock#186]
**Describe the bug**
I just generate the Swagger Petstore example at editor.swagger.io and try to import it in a project. But it fails with the error : 
`Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'void io.swagger.models.AbstractModel.addProperty(java.lang.String, io.swagger.models.properties.Property)'`

**To Reproduce**
1. Go to 'editor.swagger.io'
2. Generate the default Swagger 2.0 or OpenApi 3.0.0 Petstore example
3. Click on 'save as yaml'
3. Go back to castlemock and import the files in given project

**Expected behavior**
Import working

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 1.43

**Additional context**
Castlerock is running in a K8s pod

**Comment by karldahlgren** [comment]
Thank you @3logy for reporting this.
I have located the issue and created a fix for it. I will release a new version of Castle Mock as soon a possible.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
A new version of Castle Mock (v1.44) has now been released and can be downloaded from our webpage and from Docker Hub.

Thanks once again for reporting this.

Best regards,
Karl Dahlgren

**Comment by 3logy** [comment]
Hi @karldahlgren we are still waiting for the v1.44 on Docker Hub. Thank you for your work,

**Comment by karldahlgren** [comment]
Hi @3logy.
The latest version of Castle Mock Docker Hub is v1.44. However, I have added tag for v1.44 as well. It is now available on Docker Hub.

Sorry for the delay.
Best regards,
Karl Dahlgren
