### ISSUE TITLE
URL Query matching

### ISSUE THREAD

**Issue by crlikcngroup** [castlemock/castlemock#187]
Hi,
I have a simple gateway (using "REST API", json) I need to mock. But it is using query parameters to discriminate between the commands. For example:

```
/index.php?command=turnoff
/index.php?command=getVersion
...
```
Is possible to define different responses based on the parameter values?

I found this old issue https://github.com/castlemock/castlemock/issues/63 but I cannot see any such view. Only Header Queries tab.

I installed CastleMock today using Docker and it shows version 1.44

**Comment by GrumpyMeow** [comment]
Hi, 
This took me also a while to figure out.
The “queries” tab will only be visible if the endpoint url contains some variable “variables”.

Thus you should specify: /index.php?command={commandvar}
In the endpoint url field.

**Comment by crlikcngroup** [comment]
Aaaah, cool. Thank you very much.

Not easy to figure out. But it could do the trick.

**Comment by karldahlgren** [comment]
Thanks @GrumpyMeow!
Sorry @crlikcngroup for it being unclear. I will add this to the wiki so that it will become more clear in the future 😄

Best regards,
Karl Dahlgren
