### ISSUE TITLE
REST API for Import Project

### ISSUE THREAD

**Issue by marinog82** [castlemock/castlemock#193]
It's possible have an REST API for Import of the project?
I have check this command, related at the issue #49  :

curl -X POST "http://localhost:8080/castlemock/api/rest/core/project/import?type=SOAP" -H "accept: */*" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: multipart/form-data" -F "file=@project-soap-QrTaXl.xml;type=text/xml"

but don't work fine on the latest version of castlemock

**Comment by karldahlgren** [comment]
Hi @marinog82.
I took a look at this issue and it seems that you are using an invalid endpoint. It should be like this:

```
curl -X POST "http://localhost:8080/castlemock/api/rest/core/project/soap/import" -H "accept: /" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: multipart/form-data" -F "file=@project-soap-QrTaXl.xml;type=text/xml"
```

Please give it a try and see if it helped 😄 
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Btw, you can always see the REST API definition on the following link: http://localhost:8080/castlemock/swagger-ui.html

Best regards,
Karl Dahlgren

**Comment by marinog82** [comment]
@karldahlgren Thanks a lot ;) works

**Comment by mkysoft** [comment]
> Btw, you can always see the REST API definition on the following link: http://localhost:8080/castlemock/swagger-ui.html
> 
> Best regards,
> Karl Dahlgren

Current swagger endpoint is http://localhost:8080/castlemock/swagger-ui/
