### ISSUE TITLE
Dates are incorrect sorted in tables

### ISSUE THREAD

**Issue by karldahlgren** [castlemock/castlemock#20]
Dates in tables are incorrectly sorted when clicking on the column name.

**Comment by Honatas** [comment]
Not only dates, apparently all columns in all grids are not sorting correctly. This makes everything harder, from registering a new reponse for a service (finding the service is complicated) to check logs (not ordered by date-time).

**Comment by karldahlgren** [comment]
This issue has been been resolved with the latest version of the UI which will be part of the next release.
