### ISSUE TITLE
Queries parameter names disappear when editing & saving an existing rest-response

### ISSUE THREAD

**Issue by GrumpyMeow** [castlemock/castlemock#208]
When i have defined a rest-response with body & queries-parameters.
If i then navigate to that rest-response and do any small modification and update the response.
The parameter names of Queries disappear (also from disk in xml files).

**Comment by kavhad** [comment]
I'm getting this as well.

**Comment by karldahlgren** [comment]
Thank you @GrumpyMeow and @kavhad for reporting this.
I have located the issue and resolved it. It will be part of next release with is expected to be released this weekend.

Best regards,
Karl Dahlgren
