### ISSUE TITLE
Unable to deserialize  

### ISSUE THREAD

**Issue by Khan-Tzar** [castlemock/castlemock#209]
![test-6](https://user-images.githubusercontent.com/29702138/80619285-2cfb4100-8a4d-11ea-815a-026d7d0e4442.png)
Hello 
I used the official Docker image to setup and test Castle Mock 
I started it with this command 
docker run -d -p 8787:8080 castlemock/castlemock

Opened it and it seems worked. Tried to import project but it gave 
"**An error occurred
Unable to deserialize**"

Attached screenshots of my steps plus exported ZIP file. I tried it with Firefox 74.0.1 (64-bit)

Can you help me, please?

Then I made a new empty project and exported it. Deleted it and tried to import it from exported file. It gave me the same problem "Unable to deserialize"
![test-3](https://user-images.githubusercontent.com/29702138/80618644-5071bc00-8a4c-11ea-9993-86670297e2e9.png)
![test-4](https://user-images.githubusercontent.com/29702138/80618645-510a5280-8a4c-11ea-8c50-6141d22d7bcc.png)
![test-5](https://user-images.githubusercontent.com/29702138/80618646-51a2e900-8a4c-11ea-8723-610d261ad09a.png)
![test-1](https://user-images.githubusercontent.com/29702138/80618647-51a2e900-8a4c-11ea-84fa-d6d7d17a8079.png)
![test-2](https://user-images.githubusercontent.com/29702138/80618648-51a2e900-8a4c-11ea-9036-6ab6ab4bc865.png)

[web.zip](https://github.com/castlemock/castlemock/files/4552843/web.zip)

**Comment by karldahlgren** [comment]
Hi @Khan-Tzar.
My apologies for the late response.
Would it be possible for you to send me an example? I get this issue reported once in a while, but it seems to be related to encoding. It would really help with a small example.

Thanks!
Best regards,
Karl Dahlgren

**Comment by Khan-Tzar** [comment]
Hi @karldahlgren 

Yes sure here attached two zipped sample projects. When I try to import them in Castlemock I receive mentioned error. 
[Sample-REST-Project-soapui-project.zip](https://github.com/castlemock/castlemock/files/4632792/Sample-REST-Project-soapui-project.zip)
[Sample-SOAP-Project-soapui-project.zip](https://github.com/castlemock/castlemock/files/4632794/Sample-SOAP-Project-soapui-project.zip)

**Comment by karldahlgren** [comment]
Hi @Khan-Tzar.
The attached files seems to be exported projects from SoapUI. SoapUI project files are not supported by Castle Mock and cannot be imported.

Best regards,
Karl Dahlgren

**Comment by Khan-Tzar** [comment]
Hi @karldahlgren 
Yes I gave you SoapUI examples but when I reported the issue I attached an example from Castlemock. Here I attach it again my steps are as follow I create  a new project in Castlemock then I export created project and when i try to import it gives me unable to de serialize. You can see my screenshots. 

[caste-mock-export-soap-project.zip](https://github.com/castlemock/castlemock/files/4644273/caste-mock-export-soap-project.zip)

**Comment by karldahlgren** [comment]
Hi @Khan-Tzar.
Thank you for providing the exported project. I tried to import the project and it worked for me. Do you import the zip-file or the XML-file? Castle Mock only support the XML files and will not unpack  and import the zip-file. The zip-file is only used when exporting multiple projects, which can be a mix of either SOAP or REST projects.

Best regards,
Karl Dahlgren

**Comment by Khan-Tzar** [comment]
I think we can close this issue.
