### ISSUE TITLE
Can it differentiate response by header body for post call in Rest API  

### ISSUE THREAD

**Issue by ranjankumar87** [castlemock/castlemock#210]
Hi Team,

I am playing around Castle mock and found it very easy to use. This is more of a guidance.
I have a requirement for POST call.
Ex: /addEmployee
Header Body: 
1. 
{
"sex":"M",
"address":"US"
}

2.
{
"sex":"M",
"address":"IN"
}

I don't want to add anything as header/path/query parameter.
I mean to say nothing like this
addEmployee/1
addEmployee?id=1

 Can I differentiate response based on address?

**Comment by karldahlgren** [comment]
Hi @ranjankumar87.
Glad to hear that you find it easy to use.
I'm not completely certain what you mean with "Header Body"? It seems to me that you a looking to match based on the request JSON body. This can be achieved by using the JSON Path response strategy. You can find more information about it on our wiki: https://github.com/castlemock/castlemock/wiki/Use-Case:-REST#json-path

I hope you find this helpful.
Best regards,
Karl Dahlgren

**Comment by ranjankumar87** [comment]
Yes. You are right. I wanted match based on the request JSON body.
It worked for me and thank you very much for the quick reply and guidance.
