### ISSUE TITLE
Unable to identify SOAP operation

### ISSUE THREAD

**Issue by tomerst** [castlemock/castlemock#214]
Hey guys, I'm stuck and could really use some help.
I got some WSDL from my provider
Deploying it on castleMock shows no issues.
using it to call real provider gives back proper response
But, when trying to call this service on castleMock, I'm getting 
<error-response>
   <error-message>Unable to identify SOAP operation: EAIInterfaceServiceSoap</error-message>
</error-response>

What am I missing?

`<wsdl:definitions targetNamespace="http://EAIInterfaceWS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://EAIInterfaceWS/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://EAIInterfaceWS/">
      <s:import namespace="http://schemas.xmlsoap.org/soap/encoding/" schemaLocation="Soap_Encoding.xsd"/>
      <s:import namespace="http://schemas.xmlsoap.org/wsdl/" schemaLocation="WSDL.xsd"/>
      <s:complexType name="MsisdnIn">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" form="unqualified" name="msisdn_id" type="s:long"/>
        </s:sequence>
      </s:complexType>
      <s:complexType name="WSRet">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" form="unqualified" name="Error_Code" type="s:int"/>
          <s:element minOccurs="0" maxOccurs="1" form="unqualified" name="Error_Description" type="s:string"/>
        </s:sequence>
      </s:complexType>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="MsisdnSoapIn">
    <wsdl:part name="pIn" type="tns:MsisdnIn"/>
  </wsdl:message>
  <wsdl:message name="MsisdnSoapOut">
    <wsdl:part name="MsisdnResult" type="tns:WSRet"/>
  </wsdl:message>
  <wsdl:portType name="EAIInterfaceServiceSoapPort">
    <wsdl:operation name="Msisdn">
      <wsdl:input message="tns:MsisdnSoapIn"/>
      <wsdl:output message="tns:MsisdnSoapOut"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EAIInterfaceServiceSoapBinding" type="tns:EAIInterfaceServiceSoapPort">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <wsdl:operation name="Msisdn">
      <soap:operation soapAction="http://EAIInterfaceWS/Msisdn" style="rpc"/>
      <wsdl:input>
        <soap:body use="encoded" namespace="http://EAIInterfaceWS/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="encoded" namespace="http://EAIInterfaceWS/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EAIInterfaceService">
    <wsdl:port name="EAIInterfaceServiceSoap" binding="tns:EAIInterfaceServiceSoapBinding">
      <soap:address location="http://localhost:50351/EAIInterfaceWS/EAIInterfaceService.asmx"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>`

**Comment by karldahlgren** [comment]
Hi @tomerst.
Would it be possible for you to provide an example of how your SOAP request towards Castle Mock looks like?

Thanks.
Best regards,
Karl Dahlgren

**Comment by tomerst** [comment]
Hi Karl,
I’ve used both an autogenerated request (by SoapUI) and a real request from testing environment:
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <Header xmlns="http://schemas.xmlsoap.org/soap/envelope/"/>
    <soap:Body xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
        xmlns:types="http://EAIInterfaceWS/encodedTypes"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <ns3:Msisdn xmlns:ns3="http://EAIInterfaceWS/">
            <pIn href="#id1"/>
        </ns3:Msisdn>
        <ns3:MsisdnIn xmlns:ns3="http://EAIInterfaceWS/" id="id1" xsi:type="ns3:MsisdnIn">
            <msisdn_id xsi:type="xsd:long">77665</msisdn_id>
            <msisdn_num xsi:type="xsd:string">3443226846</msisdn_num>
            <status xsi:type="xsd:string">a</status>
            <sim_id xsi:type="xsd:long">84322</sim_id>
            <Timestamp xsi:type="xsd:dateTime">2020-05-05T10:12:45.344+02:00</Timestamp>
        </ns3:MsisdnIn>
    </soap:Body>
</soapenv:Envelope>`

**Comment by tomerst** [comment]
Anything?...

**Comment by karldahlgren** [comment]
Hi @tomerst.
Currently investigating this issue. Seems to be an issue when extracting the operation details from the WSDL. Haven't had time to look into the issue. Will continue the investigation during the weekend.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @tomerst.
I have located and fixed the issue. A new release with the fix will be released shortly (One or two days). Thank you for reporting this.

Best regards,
Karl Dahlgren

**Comment by tomerst** [comment]
Hi,
any update?...

**Comment by karldahlgren** [comment]
This issue has now been resolved and part of the latest release, 1.46.
Please give it a try.

Thanks!
Best regards,
Karl Dahlgren
