### ISSUE TITLE
Show current version of used application

### ISSUE THREAD

**Issue by Khan-Tzar** [castlemock/castlemock#215]
Is it possible to add the version of current used application, please?
In fact I searched to see what version I use and I didn't find it.  I hope I use last one 1.45 but not seen at user interface.

**Comment by karldahlgren** [comment]
Hi @Khan-Tzar.
The version of Castle Mock is always presented at the right bottom corner, e.g Castle Mock Version 1.45 (See attached screenshot).
<img width="1273" alt="version" src="https://user-images.githubusercontent.com/4678380/81511170-9580d280-9317-11ea-8800-81f35d14b0eb.png">

**Comment by Khan-Tzar** [comment]
Yes sorry my fault thanks for your help.
