### ISSUE TITLE
Some JSON Path expressions does't work with arrays

### ISSUE THREAD

**Issue by NgageX** [castlemock/castlemock#218]
Hello.
I found many problems with JSON Path expressions in Сastle Mock version. 1.48:
1. Example from a wiki does't work.

Incoming body:
{
    "store": {
        "book": [
        {
            "category": "fiction",
            "author": "Herman Melville",
            "title": "Moby Dick",
            "isbn": "0-553-21311-3",
            "price": 8.99
        },
        {
            "category": "fiction",
            "author": "J.R.R. Tolkien",
            "title": "The Lord of the Rings",
            "isbn": "0-395-19395-8",
            "price": 22.99
        }
        ]
    }
}

Mocked response:
{
    "result": "${BODY_JSON_PATH(expression="$.store.book[?(@.price > 20)].author")}"
}

Expected response:
{
    "result": "J.R.R. Tolkien"
}

Actual response:
{
    "result": "[{"category":"fiction","author":"Herman Melville","title":"Moby Dick","isbn":"0-553-21311-3","price":8.99},{"category":"fiction","author":"J.R.R. Tolkien","title":"The Lord of the Rings","isbn":"0-395-19395-8","price":22.99}]"
}

If I change the Mocked response to: "${BODY_JSON_PATH(expression="$.store.book[0]")}", I will get the same response. It looks like the code does not parse a square bracket.

2. Getting the array length doesn't work.

Incoming body: same.

Mocked response:
{
    "result": "${BODY_JSON_PATH(expression="$.store.book.length()")}"
}

Expected response:
{
    "result": "2"
}

Actual response:
{"result": ""}

When I use $.store.book.length() like JSON Path strategy, response has error: >java.lang.Integer cannot be cast to net.minidev.json.JSONArray

**Comment by karldahlgren** [comment]
Thank you for reporting this issue @NgageX.
I've resolved the issue and the fix will be part of the next release. I haven't scheduled any new release yet, but I could release a new version at the end of the week.

Would that work for you?
Thanks!
Best regards,
Karl Dahlgren

**Comment by NgageX** [comment]
Many thanks, @karldahlgren .
It will be very useful.

**Comment by karldahlgren** [comment]
The bug fix has now been released with the latest version of Castle Mock, v1.49.

Thank you once again for all your help.
Best regards,
Karl Dahlgren
