### ISSUE TITLE
Could not Generate responses from uploaded Swagger 2.0 file

### ISSUE THREAD

**Issue by doanva84** [castlemock/castlemock#219]
**Describe the bug**
I've tried many times to import/upload file to Castle-mock 1.45 (Docker) but always 'Upload error! Unable to upload or parse the file.' if checked/ticked 'Generate responses for each operation'

**To Reproduce**
0. Pre-condition
0.1 saved from http://wiremock.org/assets/js/wiremock-admin-api.json (open API 3.0) to local
0.2 use 'api-spec-converter' to convert to Swagger 2.0 (output= 'wiremock-admin-swagger2.json'

1. Go to my temp-project
2. Click on 'Upload', choose 'Swagger'
3. Scroll down to 'Choose File' (browse and select 'wiremock-admin-swagger2.json'),
4. **Tick 'Generate responses for each operation'** and Click 'Upload files' 
5. See error 'Upload error! Unable to upload or parse the file.'

**Expected behavior**
Upload & Parse then Generate responses from selected file properly.

**Screenshots**
Very similar to this screenshot: http://take.ms/boVl2

**Desktop (please complete the following information):**
 - OS: (Docker on Ubuntu x64)
 - Browser Chrome
 - Castle-mock Version: 1.45
- Other

OS | Linux
-- | --
Java version | 11.0.6
Java vendor | Oracle Corporation
Server info | Apache Tomcat/8.5.53
Server built | Mar 11 2020 10:01:39 UTC
Server version | 8.5.53.0
Total memory | 799 MB
Max memory | 8434 MB
Free memory | 691 MB
Available processors | 16

**Additional context**
If I unchecked 'Generate responses for each operation', Castle-mock could upload & parse selected file successfully (but without 'Responses'). So I guess that Castle-mock uncover some 'Response' specification statements fully.

**Comment by karldahlgren** [comment]
Hi @doanva84.
Thank you so much for reporting this issue. I managed to reproduce it and solve the issue. The bug fix will be part of the next release, which is scheduled to be released before the end of this week.

Once again, thank you so much for raising this issue.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
The bug fix has now been released with the latest version of Castle Mock, v1.49.

Thank you once again for all your help.
Best regards,
Karl Dahlgren

**Comment by doanva84** [comment]
Thank you so much, @karldahlgren for quick reaction.

As per my checking, Castlemock 1.49 could import (via Upload) for Swagger2 version of (http://wiremock.org/assets/js/wiremock-admin-api.json ) successully. However, there're some missed cases (no responses):
- /__admin/recordings/start
- /__admin/mappings/remove-by-metadata
- DELETE method of /__admin/requests/{requestId}
- DELETE method of /__admin/mappings
- /__admin/mappings/reset
- /__admin/reset
- /__admin/shutdown
- DELETE method of /__admin/mappings/{stubMappingId}
- /__admin/mappings/save
- /__admin/scenarios/reset
- /__admin/settings
- DELETE method of /__admin/requests
- /__admin/requests/reset

Please review, investigate and decide to re-open this issue or separate to new issue.
Thank you for excellent tool.

**Comment by tusharsurti** [comment]
upload swagger functionality is still not working
