### ISSUE TITLE
I don't know how to use 'Header Queries' to prevent a mock always successful

### ISSUE THREAD

**Issue by doanva84** [castlemock/castlemock#223]
**Describe the bug**
'Header Query' must prevent GET always success

**To Reproduce**
1. Go to 'Header Queries' tab of a normal GET (status code = 200)
2. Input 'Header' = 'X-Api-Key', Query = 'DEMO-KEY'
3. Scroll down and click 'Add Query' then 'Update response'
4. curl -X GET -H "X-Api-Key: DEMO-KEY123" <Address>. 
**See error**: Always get successful result (OK, code: 200). Although I've tried to set checked/unchecked full or sub-set of (Match Any, Match Case and Match Regex) for 'Header Queries'. Moreover, $ curl -X GET  <Adress> # also success although no -H "X-Api-Key..."

**Expected behavior**
curl -X GET -H "X-Api-Key: DEMO-KEY123" <Address> only return successful result for correct 'X-API-Key' (i.e. 'DEMO-KEY')

**Screenshots**

**Desktop (please complete the following information):**
- OS: (Docker on Ubuntu x64)
- Browser Chrome
- Castle-mock Version: 1.45
- Other
OS | Linux
-- | --
Java version | 11.0.7
Java vendor | Oracle Corporation
Server info | Apache Tomcat/8.5.55
Server built | May 5 2020 22:10:54 UTC
Server version | 8.5.55.0
Total memory | 635 MB
Max memory | 8434 MB
Free memory | 553 MB
Available processors | 16
Mongodb database

**Comment by karldahlgren** [comment]
Hi @doanva84.
Which response strategy are you using for your method? To get Header Queries to work you need to configure your Method to use the Header query match response strategy.

You can find more information regarding this on our wiki: https://github.com/castlemock/castlemock/wiki/Use-Case:-REST#create-mocked-responses

I hope you find this helpful.
Best regards,
Karl Dahlgren

**Comment by doanva84** [comment]
Thank you for quick supporting,
I may use 'Header queries' to prevent a mock always successful by settings 'Response strategy' as 'Header Query Match'.

It seems that we could not combine Random/Sequence strategy with 'Header Query Match'. If so, I recommend to allow multiple choices on 'Response strategy'

Thank you again for always great replies

**Comment by doanva84** [comment]
It seems that we could not combine Random/Sequence strategy with 'Header Query Match'. If so, I recommend to allow multiple choices on 'Response strategy'
