### ISSUE TITLE
JSON Path expressions with square brackets does't work

### ISSUE THREAD

**Issue by NgageX** [castlemock/castlemock#224]
Hello.
The defect https://github.com/castlemock/castlemock/issues/218 was partially fixed. Thank you for fast fix. But when I updated to Сastle Mock version. 1.49, some difficulties has appeared:

**Incoming body:**
{
"store": {
"book": [
{
"category": "fiction",
"author": "Herman Melville",
"title": "Moby Dick",
"isbn": "0-553-21311-3",
"price": 8.99
},
{
"category": "fiction",
"author": "J.R.R. Tolkien",
"title": "The Lord of the Rings",
"isbn": "0-395-19395-8",
"price": 22.99
}
]
}
}

**Mocked response:**
{
"result": "${BODY_JSON_PATH(expression="$.store.book[?(@.price > 20)].author")}"
}

**Expected response:**
{
"result": "J.R.R. Tolkien"
}

**Actual response:**
{
"result": "{category=fiction, author=Herman Melville, title=Moby Dick, isbn=0-553-21311-3, price=8.99}"
}

If I change the Mocked response to: {"result": "${BODY_JSON_PATH(expression="$.store.book[1]")}"}, I will get the same response.

**Comment by karldahlgren** [comment]
Thanks for reporting this @NgageX.
I have located where the problem is, but I haven't been able to fix it yet. I will hopefully have a fix ready in one or two days.

I will keep you posted.
Best regards,
Karl Dahlgren

**Comment by doanva84** [comment]
Hello @NgageX & @karldahlgren,
I've tried to example JSON Path on Castle-mock 1.49 (Docker version) but it seems does not work.
Please help to me to recognize mistakes for below settings.

I setup:
1. Create a json file name 'test.json' at $(pwd) (content as in https://github.com/castlemock/castlemock/wiki/JSON-Path)
2. Create a project/application/resource with GET/POST methods.
Address | http://IP:PORT/castlemock/mock/rest/project/QLfiPZ/application/cAxzyN/test1
-- | --
Response strategy | JSON Path match

3. In 'Response' of each method I've tried to Add 'JSON Path' (one of 3 samples on https://github.com/castlemock/castlemock/wiki/JSON-Path)

See error: 
1. curl -X POST http://IP:PORT/castlemock/mock/rest/project/QLfiPZ/application/cAxzyN/test1 --header "Content-Type: application/json" -d @test.json
2. curl -X GET http://IP:PORT/castlemock/mock/rest/project/QLfiPZ/application/cAxzyN/test1 --header "Content-Type: application/json" -d @test.json
3. Problems (it not return expected result as wiki example described)
- <return empty (if I set 'Body' of response is blank>
- <return {"result": "$.[?(@.expensive == 10)]"} (if I set 'Body' of response is {"result": "$.[?(@.expensive == 10)]"}>

I am so sorry for any inconveniences.

**Comment by NgageX** [comment]
Hello @doanva84 
If you want to use JSON Path as response strategy, you also need to add JSON Path at the **JSON Paths** tab in the Response.
If you want to use JSON Path of request as the part of response Body (another functional), you need not only add a Path to the Body, but also enable the checkbox **Use expressions**.

**Comment by doanva84** [comment]
Thank @NgageX for your comment,
In fact, I setup all of fields as your suggestion 
1. Response strategy = JSON Path match
2. Response
- Checked 'Use expressions' in response
- Body
```
{
	"result": "$.store.book[?(@.price < 10)]"
}
```
- JSON Paths
`$.store.book[?(@.price < 10)]`

- Otherwise as default

But 
curl -X GET http://IP:PORT/castlemock/mock/rest/project/QLfiPZ/application/cAxzyN/test1 --header "Content-Type: application/json" -d @test.json
return (same as what I put in 'Response' Body
```
{
	"result": "$.store.book[?(@.price < 10)]"
}
```

Is there any incorrect Settings from my side?

**Comment by NgageX** [comment]
@doanva84 
For expressions in Body you need to use another syntax https://github.com/castlemock/castlemock/wiki/Expression#body-json-path
Anyway it will not work now, because the current defect is not fixed.

**Comment by doanva84** [comment]
Thank you so much, @NgageX. I could see that Castle-mock works with JSON-Path partially.
In fact, I didn't review carefully the wiki contents. I am so sorry for making noises on your thread here

**Comment by NgageX** [comment]
@doanva84 glad to help you.

**Comment by spoon03** [comment]
Hello, @karldahlgren 
Any plans to fix the bug?

Thank you so much

**Comment by karldahlgren** [comment]
Hi @spoon03.
This issue should be closed since it seems that it has been resolved. Just tried it myself and it seems to work. Are you experiencing similar issues?

**Comment by spoon03** [comment]
@karldahlgren
I experiencing the problem at 1.49.
If so, I will update to the latest version. Thank!

**Comment by NgageX** [comment]
In 1.55 it's worked!
Thank you, @karldahlgren!
