### ISSUE TITLE
Can't upload SOAP with just input and/or just output

### ISSUE THREAD

**Issue by tomerst** [castlemock/castlemock#233]
Hi,
I've got this WSDL from my provider,
[ivrSyncCustomer.zip](https://github.com/castlemock/castlemock/files/4786601/ivrSyncCustomer.zip)
for which I'm getting "Upload error! Unable to upload or parse the file."

after some investigation, I see that it is due to cases like the following:
`  <wsdl:portType name="IvrSyncPort">
    <wsdl:operation name="ivrSyncCustomer">
      <wsdl:input message="tns:ivrSyncCustomerRequest" name="ivrSyncCustomerRequest">
    </wsdl:input>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IvrSyncPortSoap11" type="tns:IvrSyncPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ivrSyncCustomer">
      <soap:operation soapAction=""/>
      <wsdl:input name="ivrSyncCustomerRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>`

While this is a valid WSDL, it is currently not accepted by castleMock :(

**Comment by karldahlgren** [comment]
Hi @tomerst.
My apologies for the late response. I have actually looked into this issue quite some bit and I believed that I managed to resolve this issue. The fix will be part of next release which I hope will be released tomorrow.

Thank you so much for reporting this issue.
Best regards,
Karl Dahlgren

**Comment by tomerst** [comment]
Hi,
In which release should I expect it?
In 1.49 it is still failing...

**Comment by tomerst** [comment]
Hi, 
Was the fix released? 
I checked on latest (1.49?) and it is still failing

**Comment by karldahlgren** [comment]
Hi @tomerst.
The latest release is 1.50 and it is available both on our webpage and on Docker Hub as 'latest'.

Best regards,
Karl Dahlgren
