### ISSUE TITLE
See log inofrmation wen import RAML file 

### ISSUE THREAD

**Issue by Khan-Tzar** [castlemock/castlemock#234]
Is there a chance to see more verbose output why a RAML failed to upload?

Currently it displays "**_Upload error! Unable to upload or parse the file._** " .  Is there a log where I can go and check more details?
![upload_error](https://user-images.githubusercontent.com/29702138/85031681-a4b13680-b187-11ea-8dbb-482fae5d290e.png)

**Comment by karldahlgren** [comment]
Hi @Khan-Tzar.
My apologies for the late response.
I have improved the logging for when RAML uploads fails. It will be part of the next release.

Best regards,
Karl Dahlgren
