### ISSUE TITLE
Is castlemock generates responses from swagger based on $ref definitions?

### ISSUE THREAD

**Issue by DeRain** [castlemock/castlemock#24]
Hi, first - thank you for server - it seems very amazing and I'm looking forward use it in our new project. 

Here is example of issue:
```json
      "/items/stock":{
         "get":{
            "responses":{
               "200":{
                  "description":"OK",
                  "headers":[
                     "application/json"
                  ],
                  "schema":{
                     "type":"object",
                     "properties":{
                        "data":{
                           "$ref":"#/definitions/Item"
                        }
                     }
                  }
               }
            },
            "summary":"Get a list of Items in stock",
            "description":"Provides a list of items in stock.",
            "tags":[
               "List of Items in stock"
            ],
            "parameters":[
               {
                  "name":"model_number",
                  "in":"query",
                  "description":"Filter by model number of item added in Transport Requests.",
                  "required":false,
                  "type":"number"
               },
               {
                  "name":"stock_number",
                  "in":"query",
                  "description":"Filter by number of item added in Transport Requests.",
                  "required":false,
                  "type":"number"
               },
               {
                  "name":"item_name",
                  "in":"query",
                  "description":"Filter by item name. Case insensitive. Provides partial matching search.",
                  "required":false,
                  "type":"string"
               },
               {
                  "name":"limit",
                  "in":"query",
                  "description":"Apply limit on items list. Applied by default.",
                  "required":false,
                  "type":"number",
                  "format":"int32",
                  "default":10,
                  "example":20,
                  "minimum":10,
                  "maximum":100
               },
               {
                  "name":"offset",
                  "in":"query",
                  "description":"Apply offset on items list (for pagination purposes). Applied by default.",
                  "required":false,
                  "type":"number",
                  "format":"int32",
                  "default":0
               }
            ],
            "produces":[
               "application/json"
            ],
            "consumes":[
               "application/json"
            ]
         }
      },
```

**Comment by karldahlgren** [comment]
Hi Kirill.
Unfortunately, Castle Mock currently does not base the generated responses on $ref definition. It simply generates responses based on the defined responses in the Swagger definition. It is quite simplistic and just copies the HTTP status code and uses the description as name.

I can mark this as an improvement and implement support for this, if this is something you would like to have supported?

Cheers!

**Comment by DeRain** [comment]
Hi, @karldahlgren. It would be great to implement support of mock responses based on the schema and $ref definition (first it can be based on examples provided in each model). Unfortunately, i almost don't know java and only can help you to test this feature. Thanks!

**Comment by karldahlgren** [comment]
Hi @DeRain.
I will look into this feature first thing tomorrow. Do you have an example Swagger file with a $ref definition that I could perhaps use?

It is I that should say thank you. Your feedback to very much appreciated. Thank you.

Cheers!

**Comment by DeRain** [comment]
Hi, @karldahlgren.
Unfortunately, i can't provide swagger file from my current project, but i see a petstore example is pretty similar and it's using $ref definitions.
http://petstore.swagger.io/
http://petstore.swagger.io/v2/swagger.json

**Comment by karldahlgren** [comment]
Thanks @DeRain.
I should have this feature ready by the end of the day. I can prepare a snapshot build for you if you want to try. :)

**Comment by karldahlgren** [comment]
Hi @DeRain.
I have implemented the feature and released a new version (1.13) of Castle Mock. It is available on the webpage: https://castlemock.com.

As mentioned earlier, all feedback is appreciated.
Feel free to comment or come with feedback.
Thanks.

**Comment by karldahlgren** [comment]
I will do one more change to improve on how enum values are generated. Will try to have that fixed as soon as possible.

**Comment by DeRain** [comment]
Hey @karldahlgren. Thank you for work! Sorry for late answer - we have very tight deadlines, so i couldn't find a minute to test the new version. For now - castlemock provides an error when i'm trying to load our swagger.json. I will prepare an example for you asap. Thanks!

http://take.ms/boVl2

**Comment by karldahlgren** [comment]
Hi @DeRain.
Sorry to hear that you are getting an error. If you know what could be the root cause of the problem, then I can resolve it for you. An example would be very much appreciated. 

Thank you very much!
