### ISSUE TITLE
import multiple projects is failing

### ISSUE THREAD

**Issue by tomerst** [castlemock/castlemock#242]
Hi,
I've done an export of multiple projects from overview page.
I got some non-readable file out of it.
when I try to import it on a new castle, it fails.
on my first go i tried combination of soap+REST, but on my last attempt I tried 2 SOAP projects and it still have failed...

p.s.,
nice to have: "select all" checkbox on overview page, to select all projects at once

**Comment by karldahlgren** [comment]
Hi @tomerst.
Castle Mock will zip projects to a zip-file when exporting multiple projects. At the moment, Castle Mock does not support import multiple projects at the same time, so what you need to do is to unzip the exported file and import each project separately.

I have plans to completely rebuild the frontend for Castle Mock, so I appreciate all feedback and suggestions.

Best regards,
Karl Dahlgren
