### ISSUE TITLE
Extend Users table with 'Full Name' column

### ISSUE THREAD

**Issue by ChevTomov** [castlemock/castlemock#245]
Would it be possible to add a 'Full Name' column inside the Users table, so that the Full name of the respective user is displayed. I have noticed that the 'Full Name' was recently introduced.

![image](https://user-images.githubusercontent.com/67958466/86778355-f18b7d00-c062-11ea-9833-a0965814b895.png)

**Comment by karldahlgren** [comment]
Hi @ChevTomov.
My apologies for the late response here. I have now added the name to the user table in the user overview page.

Best regards,
Karl Dahlgren
