### ISSUE TITLE
Castlemock returning "Unable to identify SOAP operation: ConsultaSIAPEHttpPort"

### ISSUE THREAD

**Issue by bergmp** [castlemock/castlemock#246]
Hi,

I generated a mock soap web service using Castlemock. However I am receiving from Castlemock **"Unable to identify SOAP operation: ConsultaSIAPEHttpPort"**. How to fix that?
See below details to reproduce the issue.

**URL using Castlemock:** http://localhost:8080/castlemock/mock/soap/project/GY7yfy/ConsultaSIAPEHttpPort?wsdl

**WSDL:** You can get from here -> https://www1.siapenet.gov.br/WSSiapenet/services/ConsultaSIAPE?wsdl

**My request is:**
`<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Body>
        <consultaDadosFuncionais xmlns="http://servico.wssiapenet">
            <siglaSistema>A</siglaSistema>
            <nomeSistema>B</nomeSistema>
            <senha>C</senha>
            <cpf>D7</cpf>
            <codOrgao>E</codOrgao>
            <parmExistPag>b</parmExistPag>
            <parmTipoVinculo>a</parmTipoVinculo>
        </consultaDadosFuncionais>
    </Body>
</Envelope>
`

**Response is:**

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error-response>
    <error-message>Unable to identify SOAP operation: ConsultaSIAPEHttpPort</error-message>
</error-response>

```

How to fix that?

**Comment by karldahlgren** [comment]
Hi @bergmp.
Thank you for reporting this issue.
Do you mind to continue this discussion over email instead. Please send an email to karl.dahlgren@castlemock.com.

Thanks!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @bergmp.
Please read our FAQ reading submitting WSDL files before creating a new issues: https://github.com/castlemock/castlemock/wiki/FAQ#i-get-an-error-when-i-upload-my-wsdl-file-why.

Thank you very much!
Best regards,
Karl Dahlgren

**Comment by bergmp** [comment]
Hi @karldahlgren ,

Sorry about that. Please see attached the WSDL file.

[ws_siape_wsdl.txt](https://github.com/castlemock/castlemock/files/4914203/ws_siape_wsdl.txt)

**Comment by karldahlgren** [comment]
Hi @bergmp.
I made the FAQ more clear regarding submitting WSDL files. Don't want any WSDL files submitted that can be connected or associated with any company, organization or government. Please have a look at it again and re-create the ticket according to the requirement.

FAQ: https://github.com/castlemock/castlemock/wiki/FAQ#i-get-an-error-when-i-upload-my-wsdl-file-why.

Thank you for your understanding.
Best regards,
Karl Dahlgren
