### ISSUE TITLE
Redirect to login page via https

### ISSUE THREAD

**Issue by francoisle** [castlemock/castlemock#263]
Hi, we are running an instance of Castlemock on kubernetes and it can only be accessed through https.
We are running into a timeout when Castlemock initially redirect to the login page using http. 
Is there any way to tell Castlemock to use https for the login redirection ? Thanks

**Comment by karldahlgren** [comment]
Hi @francoisle.
Thank you for bringing this issue to my attention. I tried to reproduce this, but unfortunately I was unable to.

I tried to following:
1. Configure Apache Tomcat to use HTTPS
2. Access root castlemock: https://localhost:8443/castlemock

In this case I get redirected to https://localhost:8443/castlemock/login, as expected.
Am I missing something? Could you describe in further details what is happening in your setup?

Thanks!
Best regards,
Karl Dahlgren

**Comment by francoisle** [comment]
Hello @karldahlgren 
We have able to solve our issue by configuring the Tomcat server to use HTTPS as you suggested. 
We just didn't know that it was how it should be done so there's no issue anymore.
Thank you for the help.
