### ISSUE TITLE
 Is there an api to enable/disable mock methods? 

### ISSUE THREAD

**Issue by ReyyanArik** [castlemock/castlemock#266]
Hi,
We would like to use Castlemock in test automation, but we need an endpoint where we can enable / disable the mock methods that we created because we do not want to do this manually.
I have to intervene in castlemock manually without the API. But this is not  the optimal way to use castlemock in test automation I believe.
so,  Is there any API to enable/disable mock methods?  If not, is it possible to develop?
Thanks,

**Comment by karldahlgren** [comment]
Hi @ReyyanArik.
My apologies for the long response time.
Unfortunately, there isn't one at the moment, but I can definitely add support for this in an upcoming release.

I will keep you updated.
Best regards,
Karl Dahlgren

**Comment by ReyyanArik** [comment]
Hi @karldahlgren 
No problem. Thanks for your interest. I am looking forward to new release.
Thanks,

**Comment by ReyyanArik** [comment]
Hi @karldahlgren ,
Are there any updates about the upcoming release date? 
Could you please inform me if the date is certain.
Best

**Comment by karldahlgren** [comment]
Hi @ReyyanArik.
My apologies for the late response. The upcoming release of Castle Mock will feature a completely new UI re-written in React. Together with this release, we have extended the REST-API to support all features which the UI is capable of. This means that this feature will also be available in the upcoming release.

I'm hoping to have a release-build ready before the end of the year.

Thank you for suggesting this improvement.
Best regards,
Karl Dahlgren
