### ISSUE TITLE
Mock Soap service not working

### ISSUE THREAD

**Issue by emanuelrm** [castlemock/castlemock#27]
Hello,

When trying to import into soapui the soap service
Http://demo.castlemock.com:80/mock/soap/project/1vIOrW/airportSoap12
or
Http://demo.castlemock.com:80/mock/soap/project/1vIOrW/airportSoap12
?wsdl

The following error occurs: org.apache.xmlbeans.XmlException: error: does not close tag

**Comment by karldahlgren** [comment]
Hi @emanuelrm.
Castle Mock does not generate WSDL files. It only consumes them and create mocked services based on them. The original WSDL from the test server can be found in the following location: http://www.webservicex.net/airport.asmx?WSDL

I hope it helps.
Best regards,
Karl Dahlgren

**Comment by emanuelrm** [comment]
Hello @karldahlgren,

thanks for the answer,  I understood how it works now. 

Congratulations for your work
