### ISSUE TITLE
Eclipse and vscode can't import all castlemock maven projects

### ISSUE THREAD

**Issue by tobiasrdm** [castlemock/castlemock#273]
**Describe the bug**
Eclipse and vscode can't import all castlemock maven projects. The cause is more than one maven module with the same `artifactId`.
Some examples:
`core/basics` and `web/basics` has `<artifactId>basis</artifactId>`
`core/mock` and `web/mock` has `<artifactId>mock</artifactId>`
`core/mock/soap` and `web/mock/soap` has `<artifactId>soap</artifactId>`
`deploy/jetty/common` and `deploy/tomcat/common` has `<artifactId>common</artifactId>`

**To Reproduce**
1. git clone https://github.com/castlemock/castlemock.git
2. Open Eclipse IDE
3. Go to menu 'File > Import... > Existing Maven Projects'
3.1. Select castlemock directory
3.2. Click in 'Finish'
4. When eclipse complete import, several compilation errors happen.

**Expected behavior**
Eclipse and vscode import all castlemock maven projects without compilation errors.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Eclipse IDE for Enterprise Java Developers - version 2020-03 (4.15.0)
 - VS Code version 1.49.0

**Solution suggestion:**
One solution to the problem is change the `artefactId` of the modules to be unique into the castlemock project.
For example, change the `artifactId` of this modules to:
`core/basics` -> `<artifactId>castlemock-core-basis</artifactId>`
`web/basics` -> `<artifactId>castlemock-web-basis</artifactId>`
`core/mock` -> `<artifactId>castlemock-core-mock</artifactId>`
 `web/mock` -> `<artifactId>castlemock-web-mock</artifactId>`
`core/mock/soap`  -> `<artifactId>castlemock-core-mock-soap</artifactId>`
 `web/mock/soap` -> `<artifactId>castlemock-web-mock-soap</artifactId>`
`deploy/jetty/common`  -> `<artifactId>castlemock-deploy-jetty-common</artifactId>`
`deploy/tomcat/common` -> `<artifactId>castlemock-deploy-tomcat-common</artifactId>`
And the same logic for the `artifactId` of the anothers modules.

**Comment by karldahlgren** [comment]
Hi @tobiasrdm.
I wasn't aware that neither Eclipse or VSCode were able to load Castle Mock. I have some spare time over in the upcoming month. I can refactor the artifacts so that they can be imported to Eclipse and VSCode then.

Thank you for bringing this to my attention.

Best regards,
Karl Dahlgren

**Comment by tobiasrdm** [comment]
Hi @karldahlgren, thank you for answer!

For Eclipse, I found a workarround: on the import screen, click in "Advanced" and select `[groupId].[artifactId]` as "Name template". The default "Name template" is `[artifactId]`.

**Comment by karldahlgren** [comment]
Hi @tobiasrdm.
This issue has now been resolved. Thank you for reporting this.

Best regards,
Karl Dahlgren

**Comment by tobiasrdm** [comment]
Great work @karldahlgren! Thank you very nice!
