### ISSUE TITLE
Exporting SOAP project: file not found 0MtHdM.rsc

### ISSUE THREAD

**Issue by orodrigueztorres** [castlemock/castlemock#274]
I recently started using CastleMock on a Docker container. I created a REST project and a SOAP project and started mocking a bunch of services. I was able to export the REST project but I am not able to export the SOAP project. I get this error: "_Unable to find the following file: 0MtHdM.rsc_". My SOAP project has 15 WSDLs although not all ports are mocked. I created a new empty SOAP projects and was able to export it.

**Comment by karldahlgren** [comment]
Hi @orodrigueztorres.
Would it be possible for you to provide an example of a SOAP project that could not be imported? Sometimes it could be related to encoding or special characters.

In the meantime, I will try to reproduce this issue.
Thanks!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @orodrigueztorres.
Were you able to provide an example SOAP project?
If not, then I will close this issue. Feel free to re-open it if you were to experience this issue again.

Best regards,
Karl Dahlgren

**Comment by orodrigueztorres** [comment]
Hello, 

And I am sorry, a couple of days ago I logged in to provide status and apparently forgot to submit it.

Yes, I was able to resolve the issue. As you said, there were some special characters causing the problem.

Thanks again.
