### ISSUE TITLE
Docker image tags not match with github

### ISSUE THREAD

**Issue by arnou** [castlemock/castlemock#276]
**Describe the bug**
Tag released not appear in dockerhub

**To Reproduce**
After each github release, latest docker version is renamed in prior release, and latest is used for the current release

**Expected behavior**
On dockerhub, the current release should appear with tags latest and v1.xx (xx = latest github tag)

**Comment by karldahlgren** [comment]
The issue has now been resolved. Thank you for reporting this.

Best regards,
Karl Dahlgren
