### ISSUE TITLE
Receiving from castlemock "Unable to identify SOAP operation: DokumentServiceHttpSoap12Endpoint"

### ISSUE THREAD

**Issue by hrbu** [castlemock/castlemock#281]
**Describe the bug**
I'm getting the following error response:
```
<error-response>
    <error-message>Unable to identify SOAP operation: DokumentServiceHttpSoap12Endpoint</error-message>
</error-response>
```

**To Reproduce**
Using postman and post the following:
```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:aga="http://aaaaa.hhhhhhhh.dokumentService/">
    <x:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsse:UsernameToken>
                <wsse:Username>username</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">password</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
    </x:Header>
    <x:Body>
        <aga:getDocumentStructureMapping/>
    </x:Body>
</x:Envelope>
```

**Expected behavior**
Receiving a valid response.

**Additional context:**
* Using `castlemock:1.5.0`

**WSDL files or other resource attachments:**
* [obfuscated.wsdl.txt](https://github.com/castlemock/castlemock/files/5334648/obfuscated.wsdl.txt)

**Comment by karldahlgren** [comment]
Hi @hrbu.
I was unable to reproduce this issue. Were you using Castle Mock 1.5.0? I would suggest and recommend you to upgrade to the latest version, 1.51. I couldn't reproduce the issue with the latest version.

Please try with the latest version and please contact me again if you are still able to reproduce this issue.

Best regards,
Karl Dahlgren

**Comment by hrbu** [comment]
@karldahlgren ... docker hub shows `1.50` as the latest version (https://hub.docker.com/r/castlemock/castlemock/tags).

Please would you provide `1.51`?

**Comment by hrbu** [comment]
@karldahlgren ... using `v1.5.1` didn't fix my issue. But I can work around it by changing the identify strategy in the SOAP operation setting page from "element and namespace" to just "element" (you recommended this in https://github.com/castlemock/castlemock/issues/87#issuecomment-436424189). That's fine for me. Closing this.
