### ISSUE TITLE
Deployable Jar

### ISSUE THREAD

**Issue by javid90khan** [castlemock/castlemock#297]
**Is your feature request related to a problem? Please describe.**
Our infra is very much aligned to deploy executable jars instead of wars.

**Describe the solution you'd like**
Can we please publish executable jar of the app.

**Comment by karldahlgren** [comment]
Hi @javid90khan.
We do have support to build jar file for both Tomcat and Jetty. However, we do not distribute them at the moment. Could look into the possibility to distribute them in a good way. In the meantime, you can always download and build the project and use the deployable jar files directly.

Best regards,
Karl Dahlgren

**Comment by javid90khan** [comment]
Thanks a lot. I will try to build a deployable jar.
