### ISSUE TITLE
REST API to return all the project Ids

### ISSUE THREAD

**Issue by javid90khan** [castlemock/castlemock#298]
**Is your feature request related to a problem? Please describe.**
I am trying to automate the maintenance of our castlemock deployment and wish to have the ability to, create, add, or delete all the projects. I see a way to use the rest of the APIs to update the projects but don't see an API to get the Ids of all the projects.

**Describe the solution you'd like**
Can we please have an endpoint that would return all the project Ids in the system?

**Describe alternatives you've considered**
The alternative would be to manually delete all the projects before starting every import. 

**Additional context**
I would have added it myself and raised a pull request but I think the build is in a failed state on Travis CI and did not want to mess with it because Maven isn't a known territory for me.

**Comment by karldahlgren** [comment]
Hi @javid90khan. 
The upcoming release will include an extended API for Castle Mock. You will now be able to get all projects from the REST API and I believe that it should work with your solution. If not, please feel free to re-open this issue.

The upcoming release is scheduled to be released before the end of the year.

Thank you!
Best regards,
Karl Dahlgren
