### ISSUE TITLE
Query param deletion always deletes the first param

### ISSUE THREAD

**Issue by javid90khan** [castlemock/castlemock#299]
**Describe the bug**
I am mocking a REST endpoint that has serveral query params. As there is no edit option for the param value, I have to remove and create the param again. When I try to delete any param, it just deletes first param no matter which delete icon I click.

**To Reproduce**
1. Go to: Home -> REST-> Project-> Application-> Resource
2. Create resource with param e.g: /test?param1={param1}&param2={param2}
3. Click on Create method and select a GET method
4. Click Create response, click queries, select param1 and then param2 and add any value in "Query field"
5. Click Create mock request (delete works fine while creation)
6. Find the request you just create and select it to open
5. Click delete on icon on param2
4. Param1 would get deleted

**Expected behavior**
param1 should have been deleted

**Screenshots**
https://paste.pics/5359f1e1f3d8a38368422460af792d49
https://paste.pics/55adc9d3eb6c527c81bed332af6b2929

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Firefox
 - Version: 83.0 (64-bit)

**Additional context:**

**WSDL files or other resource attachments:** Please read our FAQ before submitting or reference any WSDL files or other resources: [FAQ](https://github.com/castlemock/castlemock/wiki/FAQ)

**Comment by karldahlgren** [comment]
Hi @javid90khan.
Thank you for reporting this. This issue should be resolved with the new UI in the new release.

Once again, thank you for reporting this.
Best regards,
Karl Dahlgren
