### ISSUE TITLE
typo in "Upload WADL"

### ISSUE THREAD

**Issue by AchimW** [castlemock/castlemock#30]
# Environment
version: 1.15
deployment: docker

# Error
`GET http://[HOST]:8080/castlemock/resources/js/fileUpload.js 404`
# Cause
The js file cannot be retrieved because the link to this file has a typo.
# Fix
The link should be "resource/js/FileUpload.js".

**Comment by karldahlgren** [comment]
Hi @AchimW.
Thank you very much for reporting this issue. The issue has been resolved and will be part of 1.16 release.
