### ISSUE TITLE
WSDL file import: Operation Identifier is wrong (SOAP)

### ISSUE THREAD

**Issue by dflasch** [castlemock/castlemock#300]
**Describe the bug**
When I create a new SOAP Project and upload the attached WSDL, the generated SOAP mockservice is faulty. In detail, the identifier of one of the generated operations (_obfuscatedName_) is set to one of the input parameters of the same operation (_cut/layout/fields_). As a result, the mockservice does not work, because the operation cannot be identified correctly.  
Workaround: When I change the identifier from _cut, layout or fields_ to _obfuscatedName_ by exporting, editing and importing the project file, everything works fine. 

**To Reproduce**
1. Create a new SOAP Project _\<project\>_ and upload the attached wsdl from your file system 
2. Go to Home -> _\<project\>_ -> Port _IobfuscatedPort_ -> operation _obfuscatedName_
3. The Identifier does not match the Identifier of the operation in the attached wsdl file

**Expected behavior**
The Identifier of the operation in the generated mockservice matches the Identifier of the operation in the attached wsdl file. 

**Screenshot** 
![image](https://user-images.githubusercontent.com/16955360/101062356-d67d5480-3591-11eb-9e5b-41f8099f3688.png)

[wsdl.txt](https://github.com/castlemock/castlemock/files/5637633/wsdl.txt)

**Comment by karldahlgren** [comment]
Hi @dflasch.
Sorry for the late response. Thank you for reporting this issue. Would it be possible for you to provide a sample WSDL that causes this problem? Thank you so much.

Best regards,
Karl Dahlgren

**Comment by dflasch** [comment]
Hi @karldahlgren, 

you can use the attached file wsdl.txt im my previous post. Using this wsdl and following the steps to reproduce the error, you shoud run into the same problem. Thank's a lot for your work! 

Best Regards, 
Daniel

**Comment by karldahlgren** [comment]
Hi @dflasch.
Thank you once again for reporting this issue. I have resolved the issue now and it will be part of the next release. The next release is scheduled to be released before the end of the year.

Best regards,
Karl Dahlgren
