### ISSUE TITLE
unable to update or delete user using REST API

### ISSUE THREAD

**Issue by javid90khan** [castlemock/castlemock#305]
**Describe the bug**
Tried to update user password using REST API but it breaks with an error saying PUT is not supported.
Same error when I try to delete a user.

**To Reproduce**
1. visit /swagger-ui.html 
2. Under Core section, select "/api/rest/core/user Update user"
3. Click try now and paste the following payload(replace id: with the correct Id):
{
  "email": "",
  "fullName": "admin admin",
  "id": "TQ1EWh",
  "password": "Welcome1",
  "role": "ADMIN",
  "status": "ACTIVE",
  "username": "admin"
}
4. Hit Execute
5. See error:
```
<!doctype html><html lang="en"><head><title>HTTP Status 405 ? Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 ? Method Not Allowed</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.60</h3></body></html>
```

**Expected behavior**
admin user password should have been updated.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Firefox
 - Version: 

**Smartphone (please complete the following information):**
 - Version: 83.0

**Additional context:**

**WSDL files or other resource attachments:** Please read our FAQ before submitting or reference any WSDL files or other resources: [FAQ](https://github.com/castlemock/castlemock/wiki/FAQ)

**Comment by karldahlgren** [comment]
Hi @javid90khan.
This issue is resolved in the upcoming release. Thank you for reporting this.

Best regards,
Karl Dahlgren
