### ISSUE TITLE
Problems on GZIP content encoding with SOAP

### ISSUE THREAD

**Issue by roemsi** [castlemock/castlemock#306]
**Describe the bug**
First, I'm trying CastleMock and it looks very promising for what we need. 

I wanted to record/forward a soap clients requests and record them for mocking later. It works partially, because the response gets recorded but on the client, receiveing the response from CastleMock , I get an GZIP decompression error. 
`The magic number in GZip header is not correct. Make sure you are passing in a GZip stream. ---> System.IO.InvalidDataException: The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.`

If I edit the recorded response (mock) and delete the "Content-Encoding = Gzip" Header, and use the mock, it is working. 

Even I'm not a developer, it sounds very similar to this one [ERR_CONTENT_DECODING_FAILED gzip encoding](https://github.com/castlemock/castlemock/issues/137) which was solved for REST. 

I'm sorry that I can't give source code snippets or WSDL, but I'm not allowed to by company confidential notice. 

I'm using the latest CastleMock version 1.51 as docker container, running on Docker for Windows. 

Thank you for all the work in CastleMock .

**Comment by karldahlgren** [comment]
Hi @roemsi.
Thank you so much for reporting this issue Great report! I will take a look at it as soon as I can. I will have time over during Christmas, so I hope to be able to solve a couple of issues during that time. I will keep you updated.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @roemsi.
I have added the same solution that we have applied to the REST implementation. It should hopefully do the trick. The fix will be part of the next release, which I hope can be released before the end of the year.

It would be very much appreciated if you could test and verify that the fix worked.

Thank you.
Best regards,
Karl Dahlgren

**Comment by roemsi** [comment]
Hi @karldahlgren,

Wow, that was fast. Many thanks. I'll test it as soon as the version is ready (optimum as docker image), and of course I will give feedback. 

Cheers,
roemsi

**Comment by roemsi** [comment]
Hi Karl,
First sorry for the really late reply. 
I tested it with 1.55 sadly I run in the same issue. Maybe it will be a good idea to have an option to manipulate outgoing http header in general, but for all status (forwarded and recording too) and all requests. 

It could be like the "add header UI" but for a whole project, and instead of the trash can, a check mark ,if this one should be deleted. 

Workflow:
You add a header name --> it appears in the table. Next to the name in the table, is a checkbox. If it is checked, castle is looking for this Header Name in the outgoing http header, and removes it. 

Cheers,
Christian
