### ISSUE TITLE
I can use the Faker to generate data with Regex

### ISSUE THREAD

**Issue by kmm-rafaelcosta** [castlemock/castlemock#311]
I'm trying to generate a response with Regex using Faker, is this possible?

"regex":"${FAKER(api=\"fakeValuesService().regexify(123)\, locale=\pt-BR\")}"

**Comment by karldahlgren** [comment]
Hi @kmm-rafaelcosta.

You don't need to write fakeValuesService(). regexify should be enough to get it to work :).
Could you try the following:

    ${FAKER(api=\"regexify(123)\", locale=\"pt-BR\")}

Best regards,
Karl Dahlgren

**Comment by kmm-rafaelcosta** [comment]
Thank you for help.

Now I need to know how to use it when the expression has "special" characters like this:

`${FAKER(api=\"regexify("[A-Z]{44}")\", locale=\"pt-BR\")}`

Best regards,
Rafael Costa

**Comment by karldahlgren** [comment]
I believe that you don't need any quotation marks in the regexify method call.
For example:

     ${FAKER(api="regexify([A-Z]{44})", locale="pt-BR")}

This should work better. However, I haven't use regexify so I'm not exactly certain how it functions.

Best regards,
Karl Dahlgren

**Comment by kmm-rafaelcosta** [comment]
It didn't work.

I will think of some other way to do this.

`{
    "timestamp": "2021-01-19T01:50:22.696+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/castlemock/mock/rest/project/euCYk0/application/UTN2Uu/M1869T/saldoFinalizado"
}`

Thanks for the help.
