### ISSUE TITLE
Local build instructions missing

### ISSUE THREAD

**Issue by moritz-deissner-turbinekreuzberg** [castlemock/castlemock#313]
We followed the instructions to build the frontend from [here](https://github.com/castlemock/castlemock/blob/master/CONTRIBUTING.md) but we fail to build the backend.
What do we need to execute to have the backend running locally?

**Comment by karldahlgren** [comment]
Hi @moritz-deissner-turbinekreuzberg.
You need Java 11+ and Maven to build and run the backend locally. The most straightforward approach which does not involve any IDE, such as Intellij, is to build the project with Maven and then execute one of the jars produced from the deploy-modules.

Build with Maven:

    mvn clean compile validate package

Run Jar

    java -jar deploy/deploy-jetty/deploy-jetty-jar/target/

However, many IDEs, such as Intellij, supports running applications directly. I normally just choose to create an application and choose the main class of the Jetty application:

    com.castlemock.deploy.jetty.jar.config.JarJettyApplication

You can easily create an application configuration in Intellij by doing the following steps:

    Run -> Edit Configurations -> + -> Application

* Module: deploy-jetty-jar
* Main class: com.castlemock.deploy.jetty.jar.config.JarJettyApplication

I can improve the CONTRIBUTION section and make it more clear.

I hope this helps. For more information, please see our contribution file: https://github.com/castlemock/castlemock/blob/master/CONTRIBUTING.md

Best regards,
Karl Dahlgren

**Comment by moritz-deissner-turbinekreuzberg** [comment]
Thanks.
FYI: we are trying to fix https://github.com/castlemock/castlemock/issues/100

**Comment by moritz-deissner-turbinekreuzberg** [comment]
it would be great if you could just add your answer to the CONTRIBUTING section
