### ISSUE TITLE
Unable to change the status code of a response

### ISSUE THREAD

**Issue by ChevTomov** [castlemock/castlemock#316]
Hello,

I have recently noticed that when I try to change the Status code of given response, I am unable to. It does not show any error, it looks like the change is saved, but it actually is not.

**To Reproduce**
1. Open any mock response.
2. Change the number for the HTTP Status code field.
3. Press the 'Update response' button on the bottom of the page.
4. No error is shown but on table with the Mock responses the old Status code is displayed. Also, if I open the response for Edit, the old Status code is displayed.

![image](https://user-images.githubusercontent.com/67958466/106152433-19b90580-6186-11eb-9c17-9282b282b23d.png)
![image](https://user-images.githubusercontent.com/67958466/106152492-2a697b80-6186-11eb-876a-d799341f0844.png)
After saving:
![image](https://user-images.githubusercontent.com/67958466/106152516-32292000-6186-11eb-82f6-432894977757.png)
![image](https://user-images.githubusercontent.com/67958466/106152565-3e14e200-6186-11eb-831f-0aa0870e9381.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by karldahlgren** [comment]
Hi @ChevTomov!
Thank you so much for reporting this issue. I have fixed the issue and will prepare a release shortly.

Once again, thank you.
Best regards,
Karl Dahlgren
