### ISSUE TITLE
"Queries" option missing in responses

### ISSUE THREAD

**Issue by nicohv** [castlemock/castlemock#318]
Hey team, I have a question...
I just saw that the "Queries" option for responses is missing, at least in versions 1.52 and 1.53. But it used to be present in a previous version (I don't remember exactly what version was it).

_Old version:_
![Selection_024](https://user-images.githubusercontent.com/17485763/106632416-7ccae380-655c-11eb-9723-f0812caa9606.png)

_1.53:_
![Selection_025](https://user-images.githubusercontent.com/17485763/106632454-85bbb500-655c-11eb-9787-0be24f267dd4.png)

Wonder if this is a bug or an intentional change. And, on the other hand, what should be the workaround for path params.

Thank you guys in advance.
Nicolas

**Comment by karldahlgren** [comment]
Thank you for reporting this @nicohv.
I have identified the issue and created a fix for it. I will prepare a new release today.

Best regards,
Karl Dahlgren

**Comment by nicohv** [comment]
Thank you @karldahlgren for taking care of this. Very appreciated!
