### ISSUE TITLE
Unable to edit SOAP port endpoints in v1.52

### ISSUE THREAD

**Issue by javid90khan** [castlemock/castlemock#319]
**Describe the bug**
When I import a WSDL, the port URLs are by default set to a default port. In v1.51, I had the ability to update this URL so that my application code can still hit the custom relative endpoint. In v1.52, "Update endpoint" button does not update the endpoint.

**To Reproduce**
1. Create a new SOAP project
2. Click on import WSDL and select a WSDL
3. Select the newly imported port
4. Click "Update endpoint" button
5. Enter new endpoint
6.  Click on the port now to view details and notice the URI has not changed.

**Expected behavior**
URI should have been updated to newly entered endpoint

**Screenshots**
https://paste.pics/2a400593e8695936da64cbb4ecddd088

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Firefox
 - Version: castlemock - 1.52

**Smartphone (please complete the following information):**

**Additional context:**

**WSDL files or other resource attachments:** Please read our FAQ before submitting or reference any WSDL files or other resources: [FAQ](https://github.com/castlemock/castlemock/wiki/FAQ)

**Comment by karldahlgren** [comment]
Hi @javid90khan.
The "Update endpoint" button doesn't update the address towards the SOAP application, but the forwarded endpoint. I realize how easy it is to misinterpret so I will update the button to say "Update forwarded endpoint" to make it more clear. Thank you for pointing this out :smiley:

**Comment by javid90khan** [comment]
Hi @karldahlgren,
I did notice that it is trying to update the forward endpoint in the browser console but I had updated the SOAP endpoint in v1.51 and without that ability, this breaks mocking for few of our important applications.

See this for example:
[https://paste.pics/058a23f4b4005307184bec4aa470131b](https://paste.pics/058a23f4b4005307184bec4aa470131b)

the port was: AccountSitePort
the address I needed and updated to: ACCOUNT.SITE

**Comment by karldahlgren** [comment]
Hi @javid90khan.
I'm sorry, but I'm not completely certain if I understand what you mean. In previous versions you couldn't change the endpoint for the port since it is based on the WSDL. Are you requesting the possibility to update the SOAP port URI?

Thanks!

**Comment by javid90khan** [comment]
Hi @karldahlgren,
Yes I am looking to change the SOAP port URI. 

Please refer to the below screenshot from the previous version:
[https://paste.pics/1b3a036f87a804e97f454a29f8ca420d](https://paste.pics/1b3a036f87a804e97f454a29f8ca420d)

**Comment by karldahlgren** [comment]
You are absolutely right! How could I forget that one? :thinking: 
I will try to resolve this issue as quick as possible. I will hopefully get it done sometime during the weekend.

Thanks for pointing this out.

**Comment by karldahlgren** [comment]
Hi @javid90khan!
The issue has been fixed and part of the latest release, v1.55. The latest release is now out on GitHub and on Docker Hub.

Once again, thank you for reporting this.
