### ISSUE TITLE
Castlemock responsing main page in a SOAP PORT

### ISSUE THREAD

**Issue by ivanzito** [castlemock/castlemock#33]
Hi, I'm using Castlemock through the docker image. I configured a SOAP project, so I imported the WSDL and now when I call the Castlemock through my client the response from Castlemock is 200 with content of main page. I did a lot of calls using a HTTP tool and works ok. I saw that not work with this Content-Type:: 

> application/soap+xml; charset=utf-8;action="http://com.br/EfetuarLogin"

and works with this

> application/soap; charset=utf-8;action="http://com.br/EfetuarLogin"

Bellow my request and response

> ---[HTTP request - http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap]---
Accept: application/soap+xml, multipart/related
Content-Type: application/soap+xml; charset=utf-8;action="http://com.br/EfetuarLogin"
User-Agent: JAX-WS RI 2.2.9-b130926.1035 svn-revision#5f6196f2b90e9460065a4c2f4e30e065b245e51e
<?xml version="1.0" ?><S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope" xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header></env:Header><S:Body><EfetuarLogin xmlns="http://com.br" xmlns:xs="http://www.w3.org/2001/XMLSchema"><Autenticacao><Email>email</Email><Usu>usu</Usu><Cia>2Z</Cia><Language>Portugues</Language</Autenticacao></EfetuarLogin></S:Body></S:Envelope>--------------------

Response:

> ---[HTTP response - http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap - 200]---
null: HTTP/1.1 200
Content-Language: en
Content-Length: 4248
Content-Type: text/html;charset=UTF-8
Date: Fri, 01 Dec 2017 20:32:56 GMT
Set-Cookie: JSESSIONID=845FCEF19ED22C604D2269A51CBDC1B0; Path=/castlemock; HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

> <html>
  <head>
      <title>Castle Mock</title>
      <link rel="icon" href="/castlemock/favicon.ico" type="image/x-icon" />
      <link rel="stylesheet" href="/castlemock/resources/css/bootstrap/bootstrap.min.css">
      <link rel="stylesheet" href="/castlemock/resources/css/font-awesome/css/font-awesome.css">
      <link rel="stylesheet" href="/castlemock/resources/css/main-stylesheet.css">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <script>var demoMode =false</script>
      <script type="text/javascript" charset="UTF-8" src="/castlemock/resources/js/jquery/jquery-2.1.4.min.js"></script>
      <script type="text/javascript" charset="UTF-8" src="/castlemock/resources/js/bootstrap/bootstrap.js"></script>
      <script type="text/javascript" charset="UTF-8" src="/castlemock/resources/js/main-script.js"></script>
      <script type="text/javascript" charset="UTF-8" src="/castlemock/resources/js/table.js"></script>
      <script type="text/javascript" charset="UTF-8" src="/castlemock/resources/js/tooltip.js"></script>
      <script type="text/javascript" charset="UTF-8" src="/castlemock/resources/js/demoMode.js"></script>
  </head>
    <body>
        

<header class="main-header">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar top-bar"></span>
                    <span class="icon-bar middle-bar"></span>
                    <span class="icon-bar bottom-bar"></span>
                </button>
                <a class="navbar-brand logo" href="/castlemock/web">Castle Mock  <img src="/castlemock/resources/images/logo-landscape-white.png" id="header-logo"/></a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="links nav navbar-nav navbar-right">
                    <form id="searchCommand" class="navbar-form navbar-left search" action="/castlemock/web/search" method="POST">
                        <div class="form-group">
                            <input id="query" name="query" placeholder="Search..." type="text" onfocus="this.placeholder = &#39;&#39;" value=""/>
                        </div>
                    <div>
</div></form>
                    <li><a href="/castlemock/web" data-toggle="tooltip" data-placement="bottom" title="Home"><i class="fa fa-home fa-2x"></i><span class="title"> Home</span></a></li>
                    <li><a href="/castlemock/web/me" data-toggle="tooltip" data-placement="bottom" title="anonymousUser"><i class="fa fa-user fa-2x"></i><span class="title"> anonymousUser</span></a></li>
                    <li><a href="/castlemock/web/event" data-toggle="tooltip" data-placement="bottom" title="Events"><i class="fa fa-file-text fa-2x"></i><span class="title"> Events</span></a></li>
                    
                    
                    
                    <li><a href="/castlemock/web/logout" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="fa fa-sign-out fa-2x"></i><span class="title"> Logout</span></a></li>
                </ul>
            </div>
        </div>

    </nav>
</header>
        

<div class="navigation">
    <ol class="breadcrumb">
        <li><a href="/castlemock/web">Home</a></li>
    </ol>
</div>
<div class="container">
    <section>
        <div class="content-top">
            <h1>An error occurred</h1>
        </div>
        Could not find acceptable representation
    </section>
</div>
        

<footer>
    <div class="languages">
        
    </div>

    <div class="info">
        
            
            
                <a href="https://www.castlemock.com" target="_blank">Castle Mock version. 1.16</a>
            
        
    </div>
</footer>
    </body>
</html>--------------------

**Comment by karldahlgren** [comment]
Hi @ivanzito!
Great to hear that you are using Castle Mock.
In order to use soap+xml, the port defined in the WSDL needs to be use a SOAP 1.2 binding. Which SOAP version does it say on one of the operations? SOAP 1.1 or SOAP 1.2? SOAP 1.1 uses application/soap, while SOAP 1.2 is using application/soap+xml.

There is an example of this setup on our demo server: http://demo.castlemock.com/web/soap/project/1vIOrW

Best regards,
Karl Dahlgren

**Comment by ivanzito** [comment]
Great, using another port with SOAP 1.2 I conquest consume the WS by a HTTP tool, thanks by the explanation above. But, when I call the WS through my app the same problem occurs. The CastleMock response 

>  ---[HTTP response - http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap12 - 200]---
null: HTTP/1.1 200
Content-Language: en
Content-Length: 4248
Content-Type: text/html;charset=UTF-8
Date: Fri, 01 Dec 2017 22:07:22 GMT
Set-Cookie: JSESSIONID=89B63A4A6CEEBF5584447AA04CB0D891; Path=/castlemock; HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

with a html from Castle Mock.

Thanks in advance and thank you @karldahlgren

**Comment by karldahlgren** [comment]
Does your port for SOAP 1.2 have any operations? Has these operations been mocked? Keep in mind that the operations for SOAP 1.1 and SOAP 1.2 are not the same. They are treated as completely different operations.

Would it also be possible to see your request as well?

So to summeries it:
- http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap: application/soap
- http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap12: application/soap+xml

Best regards,
Karl Dahlgren

**Comment by ivanzito** [comment]
Yeap, in reality I removed the SOAP 1.1(project). I mocked this operation too.
Below my request:

`
---[HTTP request - http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap]---
Accept: application/soap+xml, multipart/related
Content-Type: application/soap+xml; charset=utf-8;action="http://com.br/EfetuarLogin"
User-Agent: JAX-WS RI 2.2.9-b130926.1035 svn-revision#5f6196f2b90e9460065a4c2f4e30e065b245e51e
`

**Comment by karldahlgren** [comment]
The URL seems to go to http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap, which was the address to the SOAP 1.1 port. Is that correct? I would expect the URL to be http://localhost:9000/castlemock/mock/soap/project/dbbaVA/WSReservawebSoap12.

SOAP 1.1 is expecting application/soap, while SOAP 1.2 is expecting application/soap+xml. It won't find a match unless the URL and content-type is matching.

**Comment by karldahlgren** [comment]
Hi @ivanzito.
Did you manage to resolve your problem? If so, could I close this issue?

**Comment by ivanzito** [comment]
No BTW I pasted the wrong path. When I call the WS using _WSReservawebSoap12_ I receive the same response from the server and I removed the last version 1.1, so the unique project in CastleMock that I've is WSReservawebSoap12

**Comment by karldahlgren** [comment]
Could it be that your application is switching between SOAP 1.1 and SOAP 1.2? What happens if you are using both at the same time? Do you still experience the same problems?

**Comment by karldahlgren** [comment]
Hi @ivanzito.
Did you manage to resolve your issue? Can I close this issue?

Best regards,
Karl Dahlgren

**Comment by ivanzito** [comment]
@karldahlgren sorry for delay in my respone. You can close the issue. Unfortunelly I can't spend much time testing now.

Tks so much for the support 

Cheers

**Comment by karldahlgren** [comment]
Thank you for your response!
Feel free to contact me anytime if you have any further questions or issues.

Best regards,
Karl Dahlgren
