### ISSUE TITLE
500 Error when uploading WSDL

### ISSUE THREAD

**Issue by Dmitri-Filatov** [castlemock/castlemock#347]
I created a new project and tried to upload wsdl file, nothing happens visually, no error message, no info message. Debug windows in Firefox shows the following: 

XHRPOSThttp://0.0.0.0:8080/castlemock/api/rest/soap/project/WoVYCI/wsdl/file
[HTTP/1.1 500  47ms]

    	
    timestamp	"2021-03-23T20:38:43.399+00:00"
    status	500
    error	"Internal Server Error"
    message	""
    path	"/castlemock/api/rest/soap/project/WoVYCI/wsdl/file"

**Comment by antoinemeeus** [comment]
I have the same issue when using NTLM authentication.

**Comment by karldahlgren** [comment]
Hi @Dmitri-Filatov and @antoinemeeus.
Unfortunately, there is too little information to go on to investigate these issues.
Please read our FAQ for more information: https://github.com/castlemock/castlemock/wiki/FAQ#i-get-an-error-when-i-upload-my-wsdl-file-why

Thanks!

**Comment by vitalii-kalancha** [comment]
@karldahlgren i'm facing same issue using [this](https://www.dropbox.com/s/5zi4wrh38pc8ix8/GeefHandicap.wsdl?dl=0) wsdl

**Comment by karldahlgren** [comment]
Hi @vitalii-kalancha.
Please read and follow the instructions:


> However, the WSDL file NEEDS TO be obfuscate and minimized before before sending it to us. We will NOT accept any WSDL files that can be connected or associated with a company, organization or government. **Please send the WSDL file as an attachment and not as a link.**


Source: https://github.com/castlemock/castlemock/wiki/FAQ#i-get-an-error-when-i-upload-my-wsdl-file-why

Thank you!
Best regards,
Karl Dahlgren
