### ISSUE TITLE
Soap xpath expression - response selection

### ISSUE THREAD

**Issue by ganeshpalanik** [castlemock/castlemock#350]
Soap xpath expression - response selection issue

I am trying to simulate mock response using castlemock with multiple response configured for a single api. I have set the xpath expression for Partial text match. however castlemock is not picking the proper response which i expected as configured.. can some one suggest if this is an issue or my xpath needs to be corrected

xpath expression --> //RequestParameter/requestId[contains(text(),'MT')]

in requestId am sending value as MT2304122 which will vary everytime

**Comment by karldahlgren** [comment]
Hi @ganeshpalanik.
Unfortunately, I'm unable to reproduce your issue. It works for me. Have you configured the SOAP operation to use "XPath" response strategy? Go to the SOAP operation, click on "Update operation" and choose the XPath choice as response strategy.

I hope this helps.
