### ISSUE TITLE
Does Castle Mock support MTOM request?

### ISSUE THREAD

**Issue by Urahara** [castlemock/castlemock#36]
I'm trying to sending a mtom request to WSDL that i have but i keeping getting this error below:

```
<error-response>
   <error-message>getInputStream() has already been called for this request</error-message>
</error-response>
```
On log i not see any error.

**Comment by karldahlgren** [comment]
Hi @Urahara.
Unfortunately, Castle Mock does not support MTOM request at the moment. I might be able to look into it and add support for it during the weekend. 

Would it be possible for you to send me a WSDL example?

Best regards,
Karl Dahlgren

**Comment by Urahara** [comment]
Thanks, this will be great!

Here a WSDL example:
https://gist.github.com/Urahara/32cb4a29828459f897a33bad77071026

**Comment by karldahlgren** [comment]
Hi @Urahara.
Thank you very much for the WSDL example.
I have added support for MTOM requests for SOAP. Would you mind verifying that the issue has been resolved for you?
The latest snapshot build can be downloaded from https://castlemock.com/download/war/latest/castlemock.war

Thanks!
Best regards,
Karl Dahlgren

**Comment by Urahara** [comment]
woot, thanks! It's working fine.

**Comment by karldahlgren** [comment]
Great to hear!
Thank you so much for the feedback. Feel free to contact me again if you have any other issues or suggestions on improvements. Feedback is always appreciated. 

Best regards,
Karl Dahlgren
