### ISSUE TITLE
Unable to open castlemock through webbrowser "http://localhost:8080/castlemock", we are getting an error "404 not found", requested resource not available, we are able to open http://localhost/8080 successfully

### ISSUE THREAD

**Issue by krishnalohithanese** [castlemock/castlemock#377]
![image](https://user-images.githubusercontent.com/85292735/121028442-775cfe80-c7c5-11eb-84f6-2a93f798e486.png)

**Comment by karldahlgren** [comment]
Hi @krishnalohithanese.
Very hard to determine why this issue occurs. My guess is that the application fails to start. Could you provide more information about your setup and how you deploy Castle Mock? Secondly, do have any logs that you could provide?

Thanks!

**Comment by krishnalohithanese** [comment]
Yes we downloaded Castlemock war file from GIthub and deployed it via apache tomcat server, Apache tomcat server is up and running, but we are unable to launch castlemock in webbrowser.I could not see any error logs in Apache tomcat server
org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
org.apache.catalina.startup.Catalina.load Server initialization in [2734] milliseconds
org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.2]
org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\castlemock.war] has finished in [35,260] ms
org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\docs]
org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\docs] has finished in [240] ms
org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\manager]
org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\manager] has finished in [228] ms
org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\ROOT]
org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\ROOT] has finished in [109] ms
org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
org.apache.catalina.startup.Catalina.start Server startup in [37141] milliseconds

Please let me know how to pull error logs for castlemock

**Comment by krishnalohithanese** [comment]
Thanks for your response. I would really need your help to make the
castlemock up and running in my machine. We deployed castlemock war file
through Apache tomcat 10.0.2, can you please provide the steps how to do it
and prerequisites using apache tomcat

**Comment by AiratGaliev** [comment]
I had a similar problem. I deployed the application on the Apache Tomcat server v10.0.6. I had to use the latest v9 i.e. 9.0.49

**Comment by giddyhut** [comment]
Try this: in the expanded castlemock folder in webapps, hunt for WEB-INF/lib/tomcat*.jar files. Delete/change the file extension (e.g. add/change to *.bak). Then restart. Had this issue in Tomcat 9.0.19 and it worked for me. Not sure of Tomcat 10.x

**Comment by krishnalohithanese** [comment]
After changing the .jar files under folder WEB-INF/lib/tomcat*.jar to .bak files followed by restart, getting warning messages WARNING [main] org.apache.catalina.webresources.Cache.getResource Unable to add the resource at [/WEB-INF/classes/META-INF] to the cache for web application [/castlemock] because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache. And unable to launch http://localhost:8080/castlemock same 404 error

**Comment by krishnalohithanese** [comment]
I tried the above 2 ways one is upgrading to v10.0.6 and changing the tomcat.jar files to tomcat.bak extension, but none of them worked, any other suggestions

**Comment by giddyhut** [comment]
I guess downgrading to Tomcat 9 is the way to go at the moment. v1.55 (latest release) uses <tomcat.embedd.version>9.0.41</tomcat.embedd.version>
Tried bumping version to 10.0.6 and rebuilt (bypass tests) and no luck 😅

**Comment by giddyhut** [comment]
Final attempt! For Tomcat 10, place castlemock.war in $CATALINA_BASE/webapps-javaee (not webapps folder). Remove any traces of castlemock (war and/or folder) in webapps folder. Then start Tomcat.

From http://tomcat.apache.org front page:
Applications that run on Tomcat 9 and earlier will not run on Tomcat 10 without changes. Java EE based applications designed for Tomcat 9 and earlier may be placed in the $CATALINA_BASE/webapps-javaee directory and Tomcat will automatically convert them to Jakarta EE and copy them to the webapps directory. This conversion is performed using the Apache Tomcat migration tool for Jakarta EE tool which is also available as a separate download for off-line use.

Glorious! 😉

**Comment by krishnalohithanese** [comment]
Can you please confirm what is the exact version in apache tomcat 9?

**Comment by giddyhut** [comment]
9.0.41 according to build v1.55. But you can try Tomcat 10 (Final attempt comment above)

**Comment by krishnalohithanese** [comment]
tried with all the above options, but no luck, @karldahlgren , any other suggestions?

**Comment by giddyhut** [comment]
> Final attempt! For Tomcat 10, place castlemock.war in $CATALINA_BASE/webapps-javaee (not webapps folder). Remove any traces of castlemock (war and/or folder) in webapps folder. Then start Tomcat.
> 
> From http://tomcat.apache.org front page:
> Applications that run on Tomcat 9 and earlier will not run on Tomcat 10 without changes. Java EE based applications designed for Tomcat 9 and earlier may be placed in the $CATALINA_BASE/webapps-javaee directory and Tomcat will automatically convert them to Jakarta EE and copy them to the webapps directory. This conversion is performed using the Apache Tomcat migration tool for Jakarta EE tool which is also available as a separate download for off-line use.
> 
> Glorious! 😉

This worked for me, I was able to load up Castlemock login page. FYI I used JDK14 with Tomcat 10

**Comment by krishnalohithanese** [comment]
So do i need to download latest master pom.xml file "https://github.com/castlemock/castlemock/blob/master/pom.xml" update it athen build war file?

**Comment by karldahlgren** [comment]
Hi everyone!
Sorry for the delayed response. I'm currently working on a fix, so a new version will be released shortly.

**Comment by giddyhut** [comment]
> So do i need to download latest master pom.xml file "https://github.com/castlemock/castlemock/blob/master/pom.xml" update it athen build war file?

Ya get latest (master), update the version <tomcat.embedd.version>10.0.6</tomcat.embedd.version> in pom.xml then run: mvn clean install -DskipTests ...war file will be @ castlemock\deploy\tomcat\war\target ... or wait for Karl's fix :)

**Comment by karldahlgren** [comment]
Hi @krishnalohithanese and @giddyhut.
First of all, thank you everyone for the support and input! I looked into this issue and from what I can see, Spring doesn't support Apache Tomcat 10 yet, which means that Castle Mock can't be upgraded to Tomcat 10.

Reference: https://github.com/spring-projects/spring-boot/issues/22414#issuecomment-832058047

@krishnalohithanese So unfortunately, my recommendation would be to downgrade to Apache Tomcat 9 for now.

**Comment by iChicago** [comment]
I have tomcat 8 and still have the same issue.

**Comment by lvillalva** [comment]
Tienen que instalar JAVA 21, con eso funciona
