### ISSUE TITLE
Add new SoapResponseStrategy to help in predetermined test cases

### ISSUE THREAD

**Issue by mhewedy** [castlemock/castlemock#39]
Thanks for your work, really amazing.

I need to write some Integration test cases depending on castlemock, so that my application will call castelmock to return different each time for the same specific web service operation.

The point is, I cannot depend on both the existing  `SoapResponseStrategy` strategies (`RANDOM` and `SEQUENCE`), I cannot depend on `RANDOM` because my test cases need to know the result ahead so I could assert my code, and I cannot depend on `SEQUENCE` for many reasons one of them it is not a good idea to have test cases run in a certain order, they should run independently.

**The suggested solution** is to return different mock responses based on different input (XPath could used here).

BTW, `SoapOperationStatus.ECHO` is not helpful hence my application is sending real SOAP request message, and if I changed it to send some SOAP response to get it back in the request, I then changing in actual application code.

Thanks.

**Comment by mhewedy** [comment]
Here's a quick and dirty illustration of what I mean
[castlemock_mock_xpath.patch.zip](https://github.com/castlemock/castlemock/files/1704054/castlemock_mock_xpath.patch.zip) If you like the idea, I can put more effort in the code and implement the Web part as well and submit a PR

**Comment by karldahlgren** [comment]
Hi @mhewedy!
Thank you using Castle Mock, and more importantly, thank you your amazing suggestions. XPATH has long been on my list to do. I really like your approach. Looks very straightforward. If you want, we can do this in two ways:
- You make the changes and submit a PR. The only thing I would ask of you would be to sign and submit a contribution agreement (https://www.apache.org/licenses/icla.pdf).
-  I can make the changes. I can have the changes in place either today or tomorrow.

What would you prefer?
Once again, thank you very much.

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
Give me a day or two so I could try with the first option. otherwise, we can go for option 2. I'll be glad to contribute to this great software.

**Comment by karldahlgren** [comment]
Sounds great! Looking forward to see the result.
Poke me if you need any support or anything.

Best regards,
Karl Dahlgren

**Comment by koptan** [comment]
I like the idea of linking response with request in XPath way it's really helpful feature  , great work guys .

**Comment by karldahlgren** [comment]
This new XPATH feature has been implemented and merged into the develop branch.

**Comment by karldahlgren** [comment]
Thank you @mhewedy for you contribution!
Great work!

Best regards,
Karl Dahlgren
