### ISSUE TITLE
Does castlemock have support for XPATH math functions?

### ISSUE THREAD

**Issue by wedla** [castlemock/castlemock#398]
Hello, folks, 

I have been using Castlemock for a while, but only yesterday I felt the need to validate a xpath by a math function. I'm trying to validate if the system is sending a valid SOAP requisition to CastleMock. The system has to send a list of products, each one of them with an attribute called ValorTotal, as you can see below:

```
<Produtos>
     <!--Zero or more repetitions:-->
     <Produto>
        <!--Optional:-->
        <Codigo>1</Codigo>
        <Quantidade>5</Quantidade>
        <ValorTotal>0.50</ValorTotal>
     </Produto>
     <Produto>
        <!--Optional:-->
        <Codigo>2</Codigo>
        <Quantidade>1</Quantidade>
        <ValorTotal>0.50</ValorTotal>
     </Produto>
      <Produto>
        <!--Optional:-->
        <Codigo>3</Codigo>
        <Quantidade>1</Quantidade>
        <ValorTotal>0.50</ValorTotal>
     </Produto>
</Produtos>
```

In this case, I have to verify if the system is sending the list correctly. In order to do this, I tried to verify the sum of the values of all attributes called ValorTotal. Firstly, I validated the expression on [Xpather](http://xpather.com/), so I did as it follows:

![image](https://user-images.githubusercontent.com/15742763/127716623-317608c7-6c31-4a99-8cec-705bb4b677c7.png)

You can see that it works, but putting this on castlemock XPath it simply doesn't work. It doesn't recognise the expression, so castlemock returns http code 500 (there's no default response).

I want to know if math functions are recognised by the castlemock Xpath, and if they are, what am I doing wrong?

**Comment by karldahlgren** [comment]
Hi @wedla.
Thank you for creating this issue. This hasn't been supported before, but I have now added support for this. I will include this in the next release. I can have the next release ready in a couple of days. Does that work for you?

Thanks!
Best regards

**Comment by wedla** [comment]
Thank you so much, Karl! Yes, that works for me! I'll wait for the next release. Thank you very much! ;-)

**Comment by karldahlgren** [comment]
Hi @wedla.
Castle Mock v1.57 has now been released and is available on Github, our webpage and on Docker. The latest version contains this fix.

Thank you once again for reporting this.
Don't hesitate to contact me again if you experience any other problems.

Thanks!

**Comment by karldahlgren** [comment]
Hi @wedla.
I need to correct one thing. The latest version is not available on Docker Hub at the moment. They recently changed how to publish new images. I will investigate how I can publish images again. I will keep you posted.

**Comment by karldahlgren** [comment]
Hi again @wedla.
Publishing images to Docker hub now works again. The latest version is now available on Docker hub.

**Comment by wedla** [comment]
Hello, Karl! Only today, I was able to test the new feature. As you can see below, I'm already using the newer version:

![image](https://user-images.githubusercontent.com/15742763/129077961-59bfb502-31fa-45c8-ac45-643dc8794970.png)

The example I posted was by passing a json object that would be received in the request, but actually Castlemock is receiving a XML object, 'cause it mocks a SOAP API. So, the request body Castlemock receives is like this:

```
<soapenv:Body>
    <PdvOnLineTransacionar>
       <!--Optional:-->
       <acumulo>
          <Produtos>
             <!--Zero or more repetitions:-->
             <Produto>
                <!--Optional:-->
                <Codigo>91</Codigo>
                <Quantidade>1</Quantidade>
                <ValorTotal>0.50</ValorTotal>
                <Codigo>92</Codigo>
                <Quantidade>1</Quantidade>
                <ValorTotal>0.50</ValorTotal>
                <Codigo>93</Codigo>
                <Quantidade>1</Quantidade>
                <ValorTotal>0.50</ValorTotal>
             </Produto>
          </Produtos>
       </acumulo>
    </PdvOnLineTransacionar>
 </soapenv:Body>
```

And, as you can see the response obtained by using [XPather](http://xpather.com/), I get this:

![image](https://user-images.githubusercontent.com/15742763/129111012-0bbeb4ea-722e-453b-9703-9d10d78702f8.png)

But when i put the expression on XPath from CastleMock, no mock response is found, so it returns 500.

So my question is... am I doing something wrong or with SOAP requisitions the expression doesn't work? If it works, can you show some example?
