### ISSUE TITLE
Incorrect login/password message

### ISSUE THREAD

**Issue by ChevTomov** [castlemock/castlemock#399]
**Is your feature request related to a problem? Please describe.**
Can you please implement error/warning message on the login page upon login attempt with incorrect credentials? Currently, when either wrong username and/or password is provided, there is no action performed and also there is no message informing the user that the provided credentials are incorrect. The only way to know that something is not OK is to check the browser console.

**Describe the solution you'd like**
Add error message informing the user that incorrect login credentials are provided. Any similar generic message would do the job just fine.

**Comment by karldahlgren** [comment]
Hi @ChevTomov.
Thank you so much for reporting this. I have fixed the issue and the fix will be part of next release.

**Comment by karldahlgren** [comment]
This is now part of the latest release, v1.58.
Thank you once again.
Closing the ticket.
