### ISSUE TITLE
Status code of a response does not change

### ISSUE THREAD

**Issue by ChevTomov** [castlemock/castlemock#401]
**Describe the bug**
This issue is related to https://github.com/castlemock/castlemock/issues/316
We have noticed that the status of the response (or at least the text that is displayed) is changed only in the table with the responses:
![image](https://user-images.githubusercontent.com/67958466/128683623-2ad71a01-48fc-415a-8266-6feb595c2d68.png)
However, inside the response page itself the status is not changed:
![image](https://user-images.githubusercontent.com/67958466/128684553-295cd754-0a15-4c1c-bc66-c2094bf6aa61.png)
Result after chaning the status to Disabled:
![image](https://user-images.githubusercontent.com/67958466/128683831-b1e8655a-10f0-4578-932a-97edb1a8df68.png)
![image](https://user-images.githubusercontent.com/67958466/128684606-6f3a15ee-458d-418c-a380-8022f6ff0770.png)

**To Reproduce**
1. Open any response from the Mock responses table
2. Change its status to Disable
3. The status in the Mock responses table is changed but if you reopen the response, the status is unchanged

**Expected behavior**
The status of the respons should be changed inside the reponse page as well.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 92.0.4515.107

**Comment by karldahlgren** [comment]
Hi @ChevTomov!
Thank you so much for reporting this issue. Great find!
I have found the issue and created a fix for it. It will be part of next release.

**Comment by karldahlgren** [comment]
This is now part of the latest release, v1.58.
Thank you once again.
Closing the ticket.
