### ISSUE TITLE
Does the "Parameter Query" work for path parameter and query at the same time?

### ISSUE THREAD

**Issue by wedla** [castlemock/castlemock#407]
**Describe the bug**
Hello, guys! I'm mocking a GET endpoint, that receives one path and one query parameters at the same time. Something like this:

`/qrcode/pixout/order/{sale_basket_ownid}/status?textSize={textSize}`

I'm choosing the Parameter Query strategy. For the successfull response mock, the following values are being filtered:

![image](https://user-images.githubusercontent.com/15742763/130877503-8a7c60a0-0241-42a8-8b17-c3acdb7962d1.png)

You can see that I have set the filters, so the response will only be returned if the {sale_basket_ownid} exactly matches, but for {textSize} any value can be passed. However, I'm only getting 500 Internal Server Error:

![image](https://user-images.githubusercontent.com/15742763/130878829-0f256156-c141-449c-aa8b-963049124ac5.png)

I started to investigated and I figured out that it happens because of textSize query parameter. When I remove it from the URL, it works fine, it returns the correct response. I am wondering if the two filters can be used together, since they are different.

I searched for the issues already reported, and I wasn't able to find something similar. Can you help me, guys?

**To Reproduce**
1. Create a REST project;
2. Create a GET endpoint with one path and one query parameters;
3. Create a response and apply one path and one query filter parameters.
4. Set the response mock strategy to Parameter query match;
5. Make the request on a HTTP client.

**Expected behavior**
The response set for the path and query parameters.

**Desktop (please complete the following information):**
 - Windows 10
 - Google Chrome 92.0.4515.159 64 bits
 
I'm using Castlemock for docker, version 1.57.

**Comment by karldahlgren** [comment]
Hi @wedla.
My apologize for the late response.
I tried to reproduce your issue and was unfortunately unable to do that. It is possible to use both path parameters and URL queries together.

The 500 response normally indicate that it wasn't possible to find a matching response and not default response had been setup.
Would it be possible for you to make a small project where it is possible to reproduce this issue and attach it to this issue? That would help a lot.

Thank you so much!

**Comment by wedla** [comment]
Hello, @karldahlgren! Thank you for your response! I was writing a project just to show you and it did... work hahaha I'm pretty ashamed. I don't know what I did wrong when I opened the issue. I'm very sorry for the inconvenient. 

I'm closing the issue. Thank you again!
