### ISSUE TITLE
Change mock from logs page

### ISSUE THREAD

**Issue by adlet-nyussupov** [castlemock/castlemock#410]
I'm always frustrated when I see logs and cannot change mocks that are connected to them. I have to go to the project and look for this mock in order to change it.
Please, take back this feature when I can see logs and edit mocks in the same page how it was in old design. I think it will be useful not only for me, but for all users. Also, search within all projects was better as well than search in one page.

**Comment by karldahlgren** [comment]
Hi @adlet-nyussupov.
Sorry for causing some frustration, but I have added links to projects, resources, ports, operations and so on from the logs page. I would like to show the name, but I started to show the id and include links. This will be part of next release.

I hope you find this helpful and if there is ever anything else that you want or are missing, or could just make the everyday work easier, don't hesitate to create an issue.

Thank you for bringing this to my attention.
Cheers!
