### ISSUE TITLE
On demand downloadable artifacts

### ISSUE THREAD

**Issue by mhewedy** [castlemock/castlemock#45]
What I am seeking is to be able to download the war file after successful travis-ci build.

For Example, I need to download the war file as the result of this successful build: https://travis-ci.org/castlemock/castlemock/builds/341556514 

Or even to request a build on a specific git(hub) commit and then download the artifacts and use it. (so I don't need to wait for the official release to use the feature)

What is your input regarding this?

Similar to https://docs.travis-ci.com/user/deployment/releases/ but without uploading it to github, just give me a link to download it from travis itself.

**Comment by karldahlgren** [comment]
Hi @mhewedy.
Absolutely. I will see if I can upgrade the Travis script to publish the war file after a successful build. Will take a look at it later today.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @mhewedy.
I have investigated this and made some changes to the Travis script. Still testing it though. I believe that the best approach here is to configure Travis to deploy the war file to Github and mark it with a particular tag (like "Nightly build" or something similar).

I will continue implementing and testing this throughout the weekend. I hope this works for you. In the meantime I can publish nightly builds for you manually if you want that.

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
Thanks too much for your great effort. much appreciated.

**Comment by mhewedy** [comment]
I did the following:

1. pull latest from `castlemock/develop` and push it into my GitHub repo at `mhewedy/develop`
2. In https://travis-ci.org/mhewedy/castlemock I've created an env var `GITHUB_OAUTH_TOKEN`
3. I triggered a build at https://travis-ci.org/mhewedy/castlemock and I got a **draft** release created at `mhewedy/castlemock` [releases](https://github.com/mhewedy/castlemock/releases).
4. I had to put some tag manually so the release could be a public release. It is available at https://github.com/mhewedy/castlemock/releases/tag/test-build (it is picking the latest dev commit ` 18a9702`)

I am very happy with this result.

Note, steps 1 and 2 are required in my case because I don't have access to trigger a build on https://travis-ci.org/castlemock/castlemock (which is OK)

Thanks 👍

**Comment by castlemock** [comment]
Cool!
I wanted to do some work to remove the manual step at the end. I would like it to be a release and not remain as a draft. I will continue look into it throughout the weekend.

Cheers!

Best regards,
Karl Dahlgren
