### ISSUE TITLE
Cannot login if any cookie has a value with special character "ā"

### ISSUE THREAD

**Issue by valdisg** [castlemock/castlemock#463]
**Describe the bug**
Tried to login in admin panel with default username and password. Denied entry with message "Invalid credentials. Please try again." Turns out it is because I had a cookie with value "ā".

EDIT: On additional research - everything stops working if there is a cookie with value containing "ā" character.

**To Reproduce**
1. Go to 'http://{YOURIP:PORT}/castlemock/#/web/login'
2. Have a cookie with any name have a value that consists of character: "ā" (tried other special characters, had no issues).
3. Try to login with your username and password
4. See that entry is denied 

**Expected behavior**
It should let me in with the default login and password even if I have a cookie with this value

**Screenshots**
![image](https://user-images.githubusercontent.com/54055806/151403596-a2cf8796-7b39-4179-b221-acc7f4bbc1dd.png)
![image](https://user-images.githubusercontent.com/54055806/151403648-5506a88b-183b-49ed-86ca-cbff980db321.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Google Chrome
 - Version v1.62

**Comment by karldahlgren** [comment]
Hi @valdisg.
Sorry for the late response. Thank you for reporting this issue.
I looked into this issue and this seems to be related to a quite reason update in Spring Security. They have stopped allowing so called ISO control character, such as 'ā'. Unfortunately, there isn't anything I can do about this. Spring does not allow it and the web browser includes all cookies for the site automatically.

Link: https://github.com/spring-projects/spring-security/pull/8644
