### ISSUE TITLE
Is it possible to match a request and a response by a key?

### ISSUE THREAD

**Issue by oscarAtNava** [castlemock/castlemock#47]
I have an operation, findBySSN, and I pass the SSN in the request. How can I match the request value passed to a specific response defined in castlemock?

Thank you

**Comment by karldahlgren** [comment]
Hi @oscarAtNava.
Are you using SOAP? If so, I believe that you can achieve the requested behavior by using the XPath response strategy. Have you checked the following documentation entry: https://github.com/castlemock/castlemock/wiki/XPath

Please feel free to post an example of the request and response if the documentation does not help you. 

Thank you very much.
Best regards,
Karl Dahlgren

**Comment by oscarAtNava** [comment]
Thank you Karl. I got it working.

**Comment by karldahlgren** [comment]
Great to hear that it is working.
Don't hesitate to create another issue if you experience any other difficulties or need any support.
Thanks!

Best regards,
Karl Dahlgren
