### ISSUE TITLE
WSDLs with XSD does not work

### ISSUE THREAD

**Issue by asomov** [castlemock/castlemock#50]
When I try to upload a few files (WSDL, WSDL to be imported via wsdl:import, XSD) then I see files uploaded into /soap/resources/wsdl with extension *.rsc but all the files have the same content.

It looks like  the last file is copied many times.

**Comment by karldahlgren** [comment]
Hi @asomov.
Castle Mock only supports when a WSDL definition is contained within one file, and not multiple. I guess that is the issue you are referring to.

Would it be possible for you to provide an example WSDL file that is triggering this error? That would be very helpful and appreciated.
 
Thank you very much!

Best regards,
Karl Dahlgren

**Comment by asomov** [comment]
Hi Karl,
we have decided to merge files into one (it is better anyway).
It is not a problem for us anymore.
May be it is simpler to allow to choose only one file when uploading WSDL ?

I cannot provide the real file, but it contains the following definition:
<wsdl:import namespace="http://URL" location="part.wsdl"/>

**Comment by karldahlgren** [comment]
Hi @asomov.
Good to hear. Thank you for the WSDL snippet.
It is much simpler to allow one WSDL rather than multiple linked all together.

Is everything up and running for you now? Can I close this issue?

Thanks!
Best regards,
Karl Dahlgren

**Comment by asomov** [comment]
I will create another issue to allow a single upload to avoid misunderstanding

**Comment by jkransen** [comment]
This is precisely the functionality I am looking for. I commonly have a few XSD files accompanying the WSDL, often depicting different namespaces. Merging them is cumbersome, and would be an extra step, as the WSDL/XSDs are managed by a different organisation. Could this issue be reopened? It is not a bug though, it would be added functionality.

**Comment by laruche** [comment]
Hi, 
Same error for Me, find this tools (old school but working) 
You can set WDSL, and tool merge with XSD ;) 

https://github.com/pkielgithub/SchemaLightener

![image](https://user-images.githubusercontent.com/1287795/162431955-f164135c-932c-4b28-abe6-205422b3e69d.png)
