### ISSUE TITLE
Convert the mocking strategy to mock when the target WS is down

### ISSUE THREAD

**Issue by mhewedy** [castlemock/castlemock#52]
usually, we mock some services in "Recording" mock, and at random times we go the target service down, is it possible to make activate the "Mock" strategy when the target service is down?

Here's an overview of what we needs [issue_#52.zip](https://github.com/castlemock/castlemock/files/1958542/issue_.52.zip)

However my purposed solution is not smart enough, it whould be very easy and intutuive to use (if we add some hint about what FALLBACK exactly is).

if we did a more smart solution (user can decorate current strategy either forward for record or record once, etc.. with a FALLBACK strategy) but it would be hard for the user to use it.

What do you think?

**Comment by karldahlgren** [comment]
Hi @mhewedy.
I love it. Really good suggestion. An alternative way would be to have a checkbox in the operation page that say "Mock on failure". Then you can combine it however you want. What do you think about that?

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
Yes, that's better.

**Comment by karldahlgren** [comment]
Excellent! I will add it to the next release.
Once again, thank you for excellent feedback.

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
@karldahlgren 
Never mind it is okay.
Thanks for your time and effort you are really doing a great staff.

**Comment by karldahlgren** [comment]
The feature has been implemented and will be part of the next release. The release is scheduled to be released tomorrow. The "Mock on failure" option will affect the following statuses: Forward, record and record once.

Once again, thank you very much for the excellent suggestion and feedback.

Best regards,
Karl Dahlgren
