### ISSUE TITLE
get path parameter in mock response

### ISSUE THREAD

**Issue by macarlet** [castlemock/castlemock#54]
hi,
how can I retrieve a path param in the response?
ex:
method: GET
path:   
 /res1/{myParam}
response : 
{
  "myParam" : **${myParam}**
}

is there something similar already implemented?

thanks in advance

**Comment by karldahlgren** [comment]
Hi @macarlet.
It is currently not supported. With that being said, I can look into how much effort it is take implement it. I like the idea and I think that it should be that hard to hard support for it.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @macarlet.
Saw that I wrote the wrong thing the other day. What I meant to say was that it shouldn't be that hard to implement. I'm planning on including this to the next release (Which is planned to be released at the end of this week). Does that work for you?

Best regards,
Karl Dahlgren

**Comment by macarlet** [comment]
Great! It should be very useful in order to create dynamic mock response.
Thank you very much

**Comment by karldahlgren** [comment]
This feature has now been implemented and will be part of the next release. The path parameter can be retrieved by using the PATH_PARAMETER expression: ${PATH_PARAMETER(parameter="MyParameter")}.

Example:
``
{
	"id": "${PATH_PARAMETER(parameter="id")}",
}
``

Keep in mind that you have to enable expressions on the mocked response.
Thank you once again for this great suggestion and feedback.

Please feel free to create a new issue if you have any other suggestions or questions.
Best regards,
Karl Dahlgren
