### ISSUE TITLE
Upgrade the user interface

### ISSUE THREAD

**Issue by karldahlgren** [castlemock/castlemock#56]

**Comment by mhewedy** [comment]
What kind of upgrade? do you intend to just change the styles? or change the spring mvc into some kind of SPA framework?

**Comment by karldahlgren** [comment]
I wanted to update the style to make it a little bit more "stylish". I have no intention on changing any framework. Just some plain CSS styling.

I have attached a screenshot on how it looks right now for me. I wanted to do some updates on the table as well. It is currently just a prototype. Do you have any suggestions or input?

<img width="1268" alt="skarmklipp 2018-06-03 16 41 16" src="https://user-images.githubusercontent.com/4678380/40887752-834534e6-674d-11e8-8535-58b9b60e5c77.png">

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
I like the new change. I just wanted to offer help in case you were changing to angular.

**Comment by karldahlgren** [comment]
Thank you @mhewedy.
I will keep that in mind. You are the first person I will contact if there were plans on changing to Angular :)

Best regards,
Karl Dahlgren
