### ISSUE TITLE
Response mock based on the request Xpath match won't work

### ISSUE THREAD

**Issue by PaulRF** [castlemock/castlemock#578]
**To Reproduce**

Project type: SOAP
Method: Post
Response strategy: Xpath
Status: Mocked
Identify strategy: Element and namespace
Default mock response: the first response

1. Create  three mock responses  for a soap service (The Use expression checkbox set per each mock response):
the first to return 400 error code based on xpath expression (//met:SystemId[text()='111'])
the second to return 200 code based on  xpath expression (//met:SystemId[text()='222'])
the third to return 501 code  based on xpath expression (//met:SystemId[text()='333'])

2. Run a request that matches the 2nd or 3d mocks  against the mock url , for instance:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:met="http://xmlns.cm.com/ext/MetersUl/">
   <soapenv:Header/>
   <soapenv:Body>
      <met:GetMeters>
         <met:SystemId>222</met:SystemId>
      </met:GetMeters>
   </soapenv:Body>
</soapenv:Envelope>
```

**Expected behavior**
The mock response  according to  the xpath match from the request is returned 

**Actual result**
The default response is returned  always  in other words 400 code mock response ( the 1st response mock defined)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 19045.2251
 - Browser  Chrome 108.0.5359.125 

**CastleMock version**  1.64

**Comment by karldahlgren** [comment]
Hi @PaulRF.
I believe that the XPath expression might not be correct and therefore fallback to the default mock response. Could you please try the following expression and see if it works better?

`//GetMeters/SystemId[text()='222']`

Thank you so much and have a good day!`
