### ISSUE TITLE
Similar Bug 413 / 343 - REST Forward failing with 500

### ISSUE THREAD

**Issue by pgummidala** [castlemock/castlemock#579]
**Describe the bug**
REST project. I am forwarding via castlemock to an external service. The auth for that service is via an Api-Key header. I can hit the external service from Postman and I can also hit the castlemock service separately. So, I dont think connectivity is the issue

1. Do I need to create at least 1 mock service for the forward to work? I am only using Castlemock as a pass-through / re-routing
2. Is it because the custom "Api-Key" request header that is sent to castlemock endpoint is not included when forwarding to the external endpoint?

Sorry I am new to all this and didn't know where else to ask this to get a quick response. This is the response I received
{
    "timestamp": "2022-12-28T17:18:10.879+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/castlemock/mock/rest/project/YGdi7N/application/8UDYA4/initForRegUser"
}

**To Reproduce**
1. Create a forward based mocking
4. No mock responses. Nothing to filter. Just return as is. Castlemock is only used as a re-routing setup
5. Try recording and recording once also
6. See error

**Expected behavior**
Castlemock should pass the incoming request headers as is in the case of a forward and the results should be seen

**Desktop (please complete the following information):**
 - Windows 10
 - Postman
 - Version 7.30

**Comment by karldahlgren** [comment]
Hi @pgummidala.
I tried to reproduce this issue but were unable to do so. 

For testing purposes, I would recommend you to try to create a REST resource which is mocked and then create another REST resource that forward to the first REST resource. 
In that way you could verify that the forwarding works by sending a request to the REST resource which is configure to forward to the first resource and validate that the response matches the mocked resource.

You can also see request and response for each event. There you can verify that your headers are being forwarded.

A side note: What so you mean that Castlemock is only used to re-route? If that is the case, then perhaps it would be better with a proxy instead?

I hope you find this helpful.

**Comment by pgummidala** [comment]
Hi @karldahlgren,

Few questions:
1. I am not able to see any logging happening (debug / trace). Where do I see the logs?
2. In the logs section in the UI dashboard, I see the request, request headers and body. But not the response. Does that mean no response was received?
3. By re-route, I mean this. I have a server which uses IBM JDK and although all the valid certificates have been imported to the trust store, I am still not able to establish a handshake from my app sitting on the IBM server to the external REST endpoint. However, I am able to make the call to this external REST endpoint via Postman in the same machine. So, from my machine, I can hit the external service. My app, however is not able to, because of the certificate issue. So, I thought, Castlemock endpoint is http. I will set up Castlemock, set up the REST method as "forwarded" and point it to the external service. So, my IBM server calls Castlemock via http --> Castlemock calls the https external service --> Castlemock relays the JSON response to IBM server via http
4. You mentioned this is easier to do with a proxy. Are there tools available which can behave as a proxy?
Thanks for your quick response into this issue

**Comment by pgummidala** [comment]
I think I found the issue

I had about 12 services that needed to be forwarded in a project
So, I created 1 project --> 1 application --> 12 resources --> 1 method per resource ------ This did not work

I changed the structure to 
1 project --> 12 applications --> 12 resources (1 resource per application and 1 method per application) --> 12 methods

This seems to work fine
