### ISSUE TITLE
MockResponses are not imported in the correct order

### ISSUE THREAD

**Issue by DFranzen** [castlemock/castlemock#58]
When I import an xml file as a new soap project, the MockResponses are imported in a different order from the order in the file and the order of the ids. The order of the MockResponses is important for the response strategy "Sequence".

In my case I get

![image](https://user-images.githubusercontent.com/6863547/42501169-699bade2-8433-11e8-98bf-45aa83505a72.png)

The responses are ordered by their number in the file and have ids 0000xx where xx is their number and the responses are transmitted in the same order.

**Comment by karldahlgren** [comment]
Hi @DFranzen.
Thank you for raising this issue too. This issue has now been resolved. The mocked responses will now be sorted in an alphanum sorting order before they are selected. Don't mind the sorting in the tables on the SOAP operation page. The sorting internally will now be done correctly.

I have done a new release that contains this fix (v1.23). The release is available on the webpage and on Docker.
Once again, thank you for raising these issues. Very much appreciated :)

Best regards,
Karl Dahlgren

**Comment by DFranzen** [comment]
Thank you for the quick responses. That's great my first run completes now. I much appreciate the help
