### ISSUE TITLE
Type of Project

### ISSUE THREAD

**Issue by jeevitesh** [castlemock/castlemock#581]
Hello,
I need to mock external api’s in which across api url remain same, but only request body varies like mentioned below

External Api 1
URL 
/api/gatewayservice

Request body
`<Customer>
    <Request>
	XXX..XXX
</Request>
</Customer>`

External Api 2
URL 
/api/gatewayservice

Request body
`<GetPriceAndAvail>
    <Request>
     XXXXX
    </Request>
</GetPriceAndAvail>`

Please let us know what type of Project we need to create in castle mock, I’m assuming it is SOAP project, is my assumption correct ?

More over I don't have WSDL file of the external application, in this case how to approach.

Looking forward for your reply and direction
Thank you in advance

with regards
jeevitesh

**Comment by karldahlgren** [comment]
Hi @jeevitesh.
Unfortunately I don't know what type of project you should create since I don't know what you are going to mock (Either REST or SOAP).

I would recommend you to reach out to the provider of the API for more details.

Regarding WSDL file: It is required if you are going to mock a SOAP API.

**Comment by jeevitesh** [comment]
Hi,
I got to know external application is rest application, as only request body is varying across in this case how to handle in Castle mock, I thought of adding if statement in the XPATH, but how to send different response for different type of request payload.

Please share the approach how it can be handled.

Thank you in advance.

**Comment by karldahlgren** [comment]
Choose XPath as Response strategy for the method that you want to mock and in the mocked response you can add the XPath expression that needs to be fulfilled for the mocked response to be returned. Please see the Wiki for more information regarding XPath: https://github.com/castlemock/castlemock/wiki/XPath.

**Comment by jeevitesh** [comment]
Hi,
We have used different XPATH expression for two methods, but the castle mock is always redirecting to the last request.

Example

Method 1 in castle mock
`//Request/Name[text()='Karl']`

Method 2 in castle mock
`//Request/Name[text()='Jeevi']`

In the postman client even though we are sending name has Karl response is always jeevi
![image](https://user-images.githubusercontent.com/6725827/212319050-7701e2c4-e0ac-4a84-aee3-d922c5b430ab.png)

**Comment by karldahlgren** [comment]
Hi @jeevitesh.
From what I can see, you have created two separate methods (Most likely the same HTTP request method) for the same resource. A resource is a specific HTTP URL and a method is referring to a HTTP request method (GET, PUT, POST, DELETE and so on). The expected setup is to only have one unique HTTP method for each resource. From what I can see, you have created the following setup:

    Project
    |-> Application
        |-> Resource
             |-> Method (POST)
                  |-> Mock response
             |-> Method (POST)
                  |-> Mock response

However, for this to work you need to only create one method and multiple mocked response.

    Project
    |-> Application
        |-> Resource
             |-> Method (POST, Response strategy XPath)
                  |-> Mock response (XPath //Request/Name[text()='Karl'])
                  |-> Mock response (XPath //Request/Name[text()='Jeevi'])

Having multiple methods for the same resource that has the same HTTP request method, i.e GET, POST and PUT, is going to cause some inconsistent behavior and is not recommended. From my understanding, what you want is one method and multiple mocked responses. The mocked response that is being returned is dependent one the XPath expression. Please note that you can also add an optional default mock response. This response will be returned in the case none of the other XPath expression in the other mocked response are matched. 

I just tried this setup myself and it is working as expected. 
I hope you find this helpful.

**Comment by jeevitesh** [comment]
Thank you very much for the helping hand, that approach worked for us..
