### ISSUE TITLE
Response of castle mock is inconsistent 

### ISSUE THREAD

**Issue by jeevitesh** [castlemock/castlemock#590]
Hi,
We have used different XPATH expression, but the castle mock response is inconsistent. Meaning response on the 1st request is not matching subsequent 3rd and 4th request. 
We have used same url for both api's only xpath is varying
Example

Method 1 in castle mock
//Request/Name[text()='Karl']

Method 2 in castle mock
//Request/Name[text()='Jeevi']

![image](https://user-images.githubusercontent.com/6725827/217160015-a93f35d1-e79c-4649-a895-c2c0703e3e56.png)

![image](https://user-images.githubusercontent.com/6725827/217159224-85a5b0e7-a7d9-45f1-b0e2-58a1e4def67d.png)

![image](https://user-images.githubusercontent.com/6725827/217159281-3ffd18a7-b51f-44de-836b-1eaa6725a26f.png)

![image](https://user-images.githubusercontent.com/6725827/217159353-645844b1-d690-4036-86dd-be658faaf154.png)

ISSUE - First call (Expected jeevi in the response getting the same)
![image](https://user-images.githubusercontent.com/6725827/217159495-7d120fea-ff86-4e00-b65b-8325f1f7e80e.png)

Issue - 2nd call no issue Expected response 
 (Expected jeevi in the response getting the same)

Issue - 3rd call (issue)
 (Expected jeevi in the response but getting the Karl, with the same request url response is varying nothing is changed in the client)
![image](https://user-images.githubusercontent.com/6725827/217159574-b842cc17-a056-4c01-b5b4-b4d3f227f4e8.png)

Issue 4th call 
 (Expected jeevi in the response but getting the Karl, with the same request url response is varying nothing is changed in the client)
![image](https://user-images.githubusercontent.com/6725827/217159713-06ba02e3-3398-4639-bdf0-b1744accf4cf.png)

Castle mock Project collection

[https://drive.google.com/file/d/15jDL76yptjEZ9lZtFrjtTcwqtxdrwFxp/view?usp=share_link](url)

Copy paste the above url in the new window to view the xml

Client
https://castlemock.cimm2.com/castlemock/mock/rest/project/y4bDNr/application/HXTUW2/

Post method
Request body
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.castlemock.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:Request>
         <web:Name>Jeevi</web:Name>
         <web:Country>Sweden</web:Country>
      </web:Request>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by karldahlgren** [comment]
Hi @jeevitesh.
Based on the third screenshot I can see that your method is configured to use "Random" as response strategy. The method need to configured to use "XPath" as response strategy.

Please see the documentation for further information: https://github.com/castlemock/castlemock/wiki/Use-Case:-REST

**Comment by jeevitesh** [comment]
Thanks a lot that input helped us to resolve the issue
