### ISSUE TITLE
How to I pass in body for a POST call? 

### ISSUE THREAD

**Issue by taswermahmood** [castlemock/castlemock#591]
Hey Team, 

I need to **mock POST API calls,** 
Example: 
Url: https://apicastle.com/one/two/three/fourfive
Body: [{"dev":"TaswerMahmood"},{"dev":"Mahmood_Taswer"}]
Response: {
      "data": [
           {"id": "1",
           "name": "Taswer Mahmood",
           "job": "SE"},
           {"id": "2",
           "name": "Mahmood_Taswer",
           "job": "SE2"}
     ]
}

I need the mock API body to match the request body. 
I would really appreciate the help.

**Comment by karldahlgren** [comment]
Hi @taswermahmood 

You can mock REST endpoints by configuring a REST method to use JSON Path as response strategy.

Please read the documentation for more information: https://github.com/castlemock/castlemock/wiki/Use-Case:-REST#json-path
