### ISSUE TITLE
Not able to import the old project

### ISSUE THREAD

**Issue by jeevitesh** [castlemock/castlemock#597]
**Describe the bug**
We are not able to import the project XML file (9MB) which we exported from the castle mock, when we import the XML file in the castle mock we are getting "Request Entity To Large Error", and we changed the file size in application properties to 50MB but still, we are not able to import.

**To Reproduce**

1. Go to the castle mock
2. Exported the XML project file which is more than 10MB
3. Delete the project in the castle mock
4. Try to import the exported XML file
5. Observe the error attached screenshot

**Expected behavior**
The project should be imported

![image](https://user-images.githubusercontent.com/6725827/222642452-42404375-817d-4bd9-a6d1-30f298883467.png)

_Application properties changes_
![image](https://user-images.githubusercontent.com/6725827/222642524-ddc1ed58-a8fe-4af5-9528-7a95b90346a5.png)

**Desktop :**

OS: [Windows (Client browser) Linux (Server) ]
Browser [Chrome]
Version [110.0.5481.178]

**Additional context:**
NA

**WSDL files or other resource attachments:**
NA

**Comment by karldahlgren** [comment]
Hi @jeevitesh.
Please use the issue template when creating issues. Otherwise I will not be able to help you.

**Comment by jeevitesh** [comment]
Update as per the template format. Kindly help to resolve the issue

**Comment by karldahlgren** [comment]
Hi @jeevitesh.
I'm unable to reproduce this issue with a 10MB file, but can reproduce it with a file that is over 20MB (Expected behaviour). Based on the screenshot that you have provided it looks more like an error message from a proxy, a load balancer or a web server. Castle Mock does not an error message like that.
