### ISSUE TITLE
CastleMock errors a SOAP request when envelope not having a namespace qualifier

### ISSUE THREAD

**Issue by lrdevri** [castlemock/castlemock#60]
I am attempt to mock a SOAP service for a Golang application.  When it builds and sends the SOAP request, it does not use namespace qualifiers.  For example: 
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Body xmlns="http://schemas.xmlsoap.org/soap/envelope/">

I get an error response: 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error-response/>

However when I send: 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
then it works.

I would really like to use CatsleMock for our golang testing...any assistance would be appreciated

**Comment by karldahlgren** [comment]
Hi @lrdevri!
Thank you for using Castle Mock! Of course we should make sure that you can use Castle Mock :).
Just to be sure that I understood you correctly: The SOAP requests does not have namespace qualifiers. Would it be possible for you to send an example request?

This should be a quite easy thing to fix. I could probably have this done by the end of the weekend. Does that work for you?

Thank you.
Best regards,
Karl Dahlgren

**Comment by lrdevri** [comment]
This request does not work

<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Body xmlns="http://schemas.xmlsoap.org/soap/envelope/">
        <SubmitHugeBatch xmlns="http://tempuri.org/">
            <sRequestXML><![CDATA[<REQUEST RequestId="431212"></REQUEST>]]></sRequestXML>
        </SubmitHugeBatch>
    </Body>
</Envelope>

This request works:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <SubmitHugeBatch xmlns="http://tempuri.org/">
            <sRequestXML><![CDATA[<REQUEST RequestId="431212"></REQUEST>]]></sRequestXML>
        </SubmitHugeBatch>
    </soapenv:Body>
</soapenv:Envelope>

**Comment by lrdevri** [comment]
This request does not work
`<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Body xmlns="http://schemas.xmlsoap.org/soap/envelope/">
        <SubmitHugeBatch xmlns="http://tempuri.org/">
            <sRequestXML><![CDATA[<REQUEST RequestId="431212"></REQUEST>]]></sRequestXML>
        </SubmitHugeBatch>
    </Body>
</Envelope>
`

**Comment by lrdevri** [comment]
This request works:
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <SubmitHugeBatch xmlns="http://tempuri.org/">
            <sRequestXML><![CDATA[<REQUEST RequestId="431212"></REQUEST>]]></sRequestXML>
        </SubmitHugeBatch>
    </soapenv:Body>
</soapenv:Envelope>
`

**Comment by karldahlgren** [comment]
Hi @lrdevri.
Thank you for the requests. It was as I expected. I have already a fix for this issue. I can do a new release later today.

Does that work for you?

Thanks!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @lrdevri.
This issue has now been resolved. It is part of the latest release (1.24). Thank you for raising the ticket.

Best of luck :)
Best regards,
Karl Dahlgren
