### ISSUE TITLE
Require Dockerfile of this project

### ISSUE THREAD

**Issue by deveshub** [castlemock/castlemock#602]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a docker image locally but either it's not being built properly or I'm missing some steps

**Describe the solution you'd like**
It would be great if the existing Dockerfile is committed to the repo so that I can inspect and build my image or use the same Dockerfile to build a docker image out of it. 

**Describe alternatives you've considered**
I tried the following commands in Dockerfile, it created the docker image but the image failed to run with following log 
```
Mar 09, 2023 4:07:58 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.16
|  For an introduction type: /help intro

jshell> %
```
It would be great if the original Dockerfile is committed to this repository which is used to push the docker image to the Dockerhub. 
**Additional context**

**Comment by karldahlgren** [comment]
Hi @deveshub !
Have you checked the Docker repository for Castle Mock?

Repo: https://github.com/castlemock/docker

Would this help you?

**Comment by deveshub** [comment]
Oh Awesome, This helps! Sorry for missing this 😃
