### ISSUE TITLE
Incorrect encoding with none-Latin symbols

### ISSUE THREAD

**Issue by timonych** [castlemock/castlemock#61]
Hello,

The project is perfect but I have a problem with a Cyrillic symbols with upgrading or restoring the Project.

I have created the Project and there are some place where I need to user Cyrillic symbols. After upgrading o new version or after export / import All Cyrillic symbols are replacing by symbol ?.
On new version 1.24 after rewriting text via Cyrillic symbols the text becomes like code:
Exp, Иванов -> \&#1048;\&#1074;\&#1072;\&#1085;\&#1086;\&#1074; in preview mode
![2018-07-20 10_49_25-castle mock](https://user-images.githubusercontent.com/2186304/42990206-bf42a208-8c0a-11e8-84e0-caa44a1c1a25.png)

![2018-07-20 10_51_16-castle mock](https://user-images.githubusercontent.com/2186304/42990301-faf67cfc-8c0a-11e8-9a07-2814384179b8.png)

**Comment by karldahlgren** [comment]
Hi @timonych.
Thank you so much for using Castle Mock and your feedback. Much appreciated :)
I found the issue and it has now been resolved. It will be part of the next release, which is expected to be released at the end of the week.

Just keep in mind that you might have to set the Content-Type for your mocked responses depending on your setup. For example, mine was using iso-8859-1 as default. You can easily change this by adding the following header to your mocked response: Content-Type: application/soap+xml; charset=utf-8.

Feel free to contact me if you have any problems or questions.
Once again, thank you very much.

Best regards,
Karl Dahlgren
