### ISSUE TITLE
Request with Authorization parameter in Header doesn't work

### ISSUE THREAD

**Issue by agulea** [castlemock/castlemock#62]
I use castlemock through docker.
When I try to make  a request with Basic Authorization in header I got the error
`{
    "timestamp": 1532533505835,
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/castlemock/mock/rest/project/2JyYJ1/application/NBDpco/getlistinovu"
}`
I have a REST project with swagger file. The Authorization parameter is defined like this:
`"AuthorizationParam": {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string"
        }`
Can you help me please? Thanks

**Comment by karldahlgren** [comment]
Hi @agulea!
Could you send me the request that you are using? Did you include the word Basic in the authentication header?

Example: Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l

Thanks!
Best regards,
Karl Dahlgren

**Comment by agulea** [comment]
Hi @karldahlgren ,
I have a GET request:
http://192.168.99.100:8080/castlemock/mock/rest/project/2JyYJ1/application/NBDpco/getlistings?lingua=en&location=123
Headers:
Authorization: Basic dXNlclRyYWRlQjJCOnYzbjFzdXNlclRy

Thank you very much!!
Best regards,
Ana Gulea

**Comment by karldahlgren** [comment]
Hi @agulea.
I'm so sorry, I misunderstood question before. I can confirm that this seems to be a bug. I was able to reproduce this yesterday. I will try to solve it during the day and then push for a new release.

Thank you so much for raising this issue.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @agulea.
The issue should now been resolved. I have released a new version, which is available both on the webpage or on Docker hub. If you could, it would be very much appreciated if the changes made actually resolves your issues.

Thank you once again for raising this issue.
Best regards,
Karl Dahlgren

**Comment by agulea** [comment]
Hi @karldahlgren,
I tested your changes and they are working very good. Thanks for fixing it.

Best regards,
AnaG
