### ISSUE TITLE
The Mocks don't take in consideration the query string parameters

### ISSUE THREAD

**Issue by agulea** [castlemock/castlemock#63]
I have a GET method that use query string parameters but I'm not able to define mocks based those parameters. The mock can be defined only per path.
Do you take in consideration it for the next releases? It would be great to have the possibility to define mock based on query string parameters also.
Thank you very much. The idea of this project is great, I appreciate it.

Best regards, 
Anamaria Gulea

**Comment by karldahlgren** [comment]
Hi @agulea.
I've been thinking the same. It would be nice to match a response based on incoming query parameters. Do you have a suggestion on how this could be configured?

Thank you for the feedback!
Best regards,
Karl Dahlgren

**Comment by agulea** [comment]
HI @karldahlgren,
 
The number of parameters is different for each method, so an option could be to configure them using a json instead of use a different textbox for each one.
Thank you.

Best regards,
AnaG

**Comment by agulea** [comment]
Hi @karldahlgren ,

Another type of mock which would be great to have is for POST requests, a mock based on body content. I have some examples of methods which use the same path but based on body content I get a different response.
What do you think?

Thank you very much.
Best regards,
AnaG

**Comment by karldahlgren** [comment]
Hi @agulea.
I like both ideas! We already have XPath matching for SOAP project. We could do something similar for REST.
I will start looking into these as soon as I can. However, I have a very limited amount of time at the current moment. Things will get back to normal around the middle of August. So I wouldn't expect these to be implemented before that unfortunately.

I hope that works for you.
Thanks!
Best regards,
Karl Dahlgren

**Comment by agulea** [comment]
Great @karldahlgren !! Thank you very much.

**Comment by jhonatanforero** [comment]
Hi @karldahlgren 
Request Matcher for Rest Project Its a Great Idea!

**Comment by jhonatanforero** [comment]
Hi @karldahlgren 
Some date to release the Request Matcher for REST?

**Comment by karldahlgren** [comment]
Hi @jhonatanforero.
My goal is to have this done by the end of the week.

I hope that works for you.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @jhonatanforero.
Still working on this, but almost done. I hope that I will get this done as soon as possible.
I will keep you posted on this.

My apologies for the delay on this.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
This feature has now been implemented and will be part of the next release. The next release will be released tomorrow.

I'm sorry for the delay and I hope you enjoy the feature.
Don't hesitate to contact me if you have any questions or further feedback.

Thank you very much.
Best regards,
Karl Dahlgren

**Comment by jhonatanforero** [comment]
Hi Karl

Great job! Thanks for all.

**Comment by karldahlgren** [comment]
Hu @jhonatanforero.
Castle Mock 1.30 has now been released.
Please feel free to contact me again if you have any feedback or further suggestions. Always appreciated :)

Thank you!
Best regards,
Karl Dahlgren

**Comment by spartancr8** [comment]
Hi @karldahlgren:

I'm checking the application concerning the request match in REST, but there's no field to set the match, or similar to the field present in the SOAP services.

By any chance, do you have any documentation that may allow us to set the request match in REST properly? I'm still afraid I might be missing something, but so far I didn't find the way.

Thank you in advance and my best regards,

**Comment by karldahlgren** [comment]
Hi @spartancr8.
My apologies for the lack of documentation. I can only blame it on lack of time. 
Anyway, I will try to describe it the best I can in this response.

The path parameters will be extracted and presented when creating or modifying a REST mock response. A path parameter is identified with {} in the URL. Example /user/{userId}/order/{orderId}. The following parameters should be shown in the mock response view: userId and orderId.

<img width="1071" alt="skarmklipp 2018-10-17 23 41 34" src="https://user-images.githubusercontent.com/4678380/47118017-52a76780-d266-11e8-84b6-c6dc9a4150db.png">

There are three options:

- Match any: Match any incoming parameter
- Match case: Make it case sensitive. The default behavior is that it ignores case
- Match regex: Use regex pattern to match with the incoming parameter


The way it works is that the incoming parameters will be extracted from the URL and matched one by one. If all the query parameters match one way or another, the mocked response will be chosen. You can choose to use a default mocked response in case no mocked response matches. This is configured in the Rest Method update view.

I hope you find this response helpful. Don't hesitate to ask more questions if you want me to clarify more.

Thanks!
Best regards,
Karl Dahlgren

**Comment by spartancr8** [comment]
Hi @karldahlgren:

Thank you very much for the explanation. It will help me a lot!
Besides, I wanted to ask something else: It would be even more helpful if the match could be done also by http method (get, put, post, and so on...) and/or by data sent in the request (one attribute at least). Is there planned any development that might accomplish what I specified above?

Thank you again for your amazing help with this. 

Regards,

Carlos

**Comment by karldahlgren** [comment]
Hi @spartancr8.
Glad I could help =)
Could you elaborate what you mean with match by method? Because today the incoming request is mainly mapped towards a REST method (i.e GET, POST, PUT and so on). All the mocked responses belong to a particular method.
The second question is very interesting. Do you mean that you map towards a particular field in the request body? We have support for this for SOAP, but not REST (See https://github.com/castlemock/castlemock/wiki/XPath). Is this what you were referring to?

Thank you very much!
Best regards,
Karl Dahlgren

**Comment by spartancr8** [comment]
Hi @karldahlgren:

Exactly, that's what I'm asking. About a particular field in the request body.

**Comment by CamiloCode** [comment]
@karldahlgren hi, is it possible to include that feature mentioned above? "The second question is very interesting. Do you mean that you map towards a particular field in the request body? We have support for this for SOAP, but not REST (See https://github.com/castlemock/castlemock/wiki/XPath). Is this what you were referring to?"

**Comment by CamiloCode** [comment]
this is important as we are mocking REST services and we want to match those requests with identication id numbers and so on. I'll be glad if you can include this a new version

**Comment by karldahlgren** [comment]
Hi @CamiloCode.
Thank you for bringing this to my attention again. Unfortunately, it had slipped my mind. My apologies. I can create a new ticket for this issue and refer back to this one. I agree that this feature would be very helpful. Unfortunately, implementing this might be little more tricker than how it is done for SOAP, but not impossible.

Thank you once again. I will prioritize this issue.
Best regards
Karl Dahlgren

**Comment by ishwaryaAug** [comment]
currently i am using castlemock 1.36 version...in that i am trying to mock the response based on query param..as  you stated earlier i am unable to find the query param mock response view in Rest Method update view.
it would be help full if u give has step by step guide to setup mock response for rest service.

<img width="912" alt="updatemtdview1" src="https://user-images.githubusercontent.com/25953713/52928485-f4020f80-3365-11e9-9e1e-fa233f26feb8.png">
<img width="666" alt="updatemtdview2" src="https://user-images.githubusercontent.com/25953713/52928487-f6fd0000-3365-11e9-81ab-5b073110cafb.png">

**Comment by karldahlgren** [comment]
Hi.
Query parameters are defined in the URL in the following manner: /{param1}/{param2}.
Instead of having the actual value, you use these in the URL. We have an example in our test application: https://castlemock.herokuapp.com/web/rest/project/EqbLQU/application/QLP2Nk/resource/WgO9j8

Standard username and password. The application is in demo mode, which means you can't modify any values, but you can see the mocked application has been setup.

I hope this help. Don't hesitate to contact me again if you need further assistance.

Best regards,
Karl Dahlgren

**Comment by ishwaryaAug** [comment]
thx Karl..it is working fine.if i am using the url in following manner :/{param1}/{param2}. query param mock response tab is viewable and i can able to get the mock response based on the path param value.
but i am using the url in the following pattern **?userId=ABCD0011**,in this case i am not able to acheive response as expected.
is there any configuration i m missing.please let me know.

**Comment by karldahlgren** [comment]
Hi @ishwaryaAug.
Unfortunately, we don't have support for query string as a response strategy today. However, this is something we have considered adding and can add if it is requested. Is this something you would like us to add support for?

Thanks!

Best regards,
Karl Dahlgren

**Comment by ishwaryaAug** [comment]
Hi Karl,

It would be great if you include it in your upcoming version.

thanks!!

**Comment by boo2311** [comment]
Hi saiello/Karl Dahlgren,
                                       I have a GET service which needs the response to be mocked based on the query String parameter. My URL is like "/rest/scbFMFXRates/v1/rs/getRates?country={country}&buyCurrency={buyCurrency}". I have created a mock response with Response Strategy as "Query Match" with buyCurrency as response parameter and attached the screenshot . But the mock response was not picked. Kindly help to know what i am missing. Thanks
![Query_Match](https://user-images.githubusercontent.com/53167477/61613041-dcfd7b80-ac7d-11e9-85b0-7316bd56fd27.jpg)

**Comment by castlemock** [comment]
Hi!
In this case you have two parameters that needs to be matched to return a mocked response. Try to include country query and set it to match any. In this case country will be matched to any and buyCountry will mainly be used to determine which mocked response should be returned.

I hope this helps.
(Btw, I’m currently out traveling so the response time might vary at times)

Best regards,
Karl Dahlgren

Skickat från min iPhone

**Comment by boo2311** [comment]
Hi Karl,
            As you suggested, i have configured the query parameters and the service is working fine now. But i have an issue further and a feature(enhancement) for you to look into.
Issue:
Once i created the mock response with query parameters and response body, it is working as expected. But after sometime if i want to change any value in the response body and update the response, the query params which i configured earlier has gone as per the screenshot attached. So i have to delete all the query parameters and configure again.

Enhancement Feature Suggestion:
                         It will be very helpful if you can provide an option to edit the parameters configuration.
Because deleting and recreating the parameters consumes lot of time.
Thanks in advance !!
![Param_Err](https://user-images.githubusercontent.com/53167477/61691156-90cb3d80-ad48-11e9-86a7-a23dee080b00.jpg)

**Comment by ranjankumar87** [comment]
Hi Team,
Currently using version 1.45. Want to configure endpoint based on query parameters.
Wanted two responses for two countries India & US (getCustomer?country=IN)

I have configured resource getCustomer?country={country} and responses for two countries.
But giving same response, for all these URL
1. http://192.168.1.5:8080/castlemock/mock/rest/project/LenS6e/application/e0sj58/getCustomer?country=US
2. http://192.168.1.5:8080/castlemock/mock/rest/project/LenS6e/application/e0sj58/getCustomer?country=IN
3. http://192.168.1.5:8080/castlemock/mock/rest/project/LenS6e/application/e0sj58/getCustomer?name=ranjan
4. http://192.168.1.5:8080/castlemock/mock/rest/project/LenS6e/application/e0sj58/getCustomer
 
Can you please tell what mistake I am doing?
Attached screenshots.
![Capture1](https://user-images.githubusercontent.com/64093792/79892519-54845500-8420-11ea-8db8-bf08d0282cf2.PNG)
![Capture2](https://user-images.githubusercontent.com/64093792/79892527-55b58200-8420-11ea-83d7-be0753a080ab.PNG)
![Capture3](https://user-images.githubusercontent.com/64093792/79892529-564e1880-8420-11ea-82b3-cbd9f169c0f8.PNG)
