### ISSUE TITLE
How can the created projects be stored  in docker?

### ISSUE THREAD

**Issue by agulea** [castlemock/castlemock#64]
Hi,
I use castle through docker but it looks like the created projects are removed if I restart the docker-machine on Windows.
I added this code in docker-compose.yml:
`castle-mock:
    image: castlemock/castlemock
    ports:
      - "8080:8080"
    volumes:
      - ${PATH}/castle-mock:/root/.castlemock`

Do you have any idea?

Thank you very much.
Best regards,
AnaG

**Comment by karldahlgren** [comment]
Hi @agulea.
I'm not certain if it works differently on Windows, but you can find more information about Docker persistence on Castle Mock's webpage: https://castlemock.com/docker/. See under persistence. I believe that this is what you are looking for.

I hope it help!
Don't hesitate to contact me if you have any further questions.

Best regards,
Karl Dahlgren

**Comment by agulea** [comment]
Hi @karldahlgren ,
The problems was that docker machine looses volume data on restart because the files added by castle was written only on virtual path, I forgot to share to Virtual Box the directory used for files added by the castle. Now it works fine.

Thanks.
Best regards,
Ana Gulea
