### ISSUE TITLE
Is there Any chance to work with Oracle WebLogic ?

### ISSUE THREAD

**Issue by timonych** [castlemock/castlemock#65]
Hi again,

I have tried to use the Application with Oracle WebLogic, but I received an error when I have tried to open the page.

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Aug 03 09:41:30 MSK 2018
There was an unexpected error (type=Internal Server Error, status=500).
weblogic.servlet.jsp.CompilationException: Failed to compile JSP /WEB-INF/views/login.jsp login.jsp:17:18: The include file was not found. <%@ include file="includes.jspf"%> ^-------------^ login.jsp:17:18: The include file was not found. <%@ include file="includes.jspf"%> ^-------------^

I have searched is there any page and have found it in WEB-INF\lib\com.castlemock.web-basis-1.27.jar - in other words it's Real-Time Compilation, is it ?

If it possible I can test it in our systems,

**Comment by karldahlgren** [comment]
Hi @timonych.
Castle Mock is currently not support with Oracle WebLogic. However, I could investigate adding support for it in future releases. I'm currently out traveling and won't be able to do a lot for another week or so. I can start looking into this as soon as I'm back.

Does that work for you?

Thanks!
Best regards,
Karl Dahlgren

**Comment by timonych** [comment]
I have already using Castlemock with Tomcat, but it's not ts usefull to contole it such as WebLogic.
In other case with Oracle WebLogic you can control each service via AdminServer and web interface of WebLogic.

So, this is not critical for me, but it will be perfect in future. 

Also, can you add 20$ in donate page?

**Comment by timonych** [comment]
Also, I have succesfull deployed the Application with Number of Release, but Oracle have made link with the name Application. So, if I want to test new version if I will publish new version it can damaged old version.

When You will try to add Oracle WebLogic support, I think it necessary to add versions in name or something else to make unique each new version.

Also, I can test each moment with it in future if it's necessary.

**Comment by karldahlgren** [comment]
I appreciate your feedback! It is very valuable. I will definitely look into this.

Thank you very much!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @timonych.
I believe I'm more or less done with this. Just need to test it and verify it.
Just wanted to keep you posted.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
This issue has been implemented and will be part of the next release.

**Comment by timonych** [comment]
> This issue has been implemented and will be part of the next release.

Hello again, @karldahlgren !

I have installed the last version, 1.30 on Oracle Weblogic, but it doesn't work :(

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Oct 09 09:12:34 MSK 2018
There was an unexpected error (type=Internal Server Error, status=500).
weblogic.servlet.jsp.CompilationException: Failed to compile JSP /WEB-INF/views/login.jsp login.jsp:17:18: The include file was not found. <%@ include file="includes.jspf"%> ^-------------^ login.jsp:17:18: The include file was not found. <%@ include file="includes.jspf"%> ^-------------^
