### ISSUE TITLE
Issues with JSON Path

### ISSUE THREAD

**Issue by luisfilsilva** [castlemock/castlemock#667]
Hi guys,

I don't believe this is an issue, but rather lack of experience.. I'm trying to use "Add JsonPath" on a Mock Response. What I assumed, but doesn't seem to be right, is that a JsonPath can be used to pick a Mock Response, i.e., if the expressions match, it picks that body message. However, that is not what I'm seeing..  Can please tell me what I'm doing wrong? Thanks!!

![image](https://github.com/castlemock/castlemock/assets/37806453/3dd8d79e-9f73-493c-a4c3-f9abdc74dbd8)

`{
  "store": {
    "book": [
      {
        "category": "fiction",
        "author": "J. K. Rowling",
        "title": "Harry Potter and the Philosopher's Stone",
        "isbn": "0-747-53274-5",
        "price": 5.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J.R.R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "games": {
      "title": "World Of Warcraft",
      "developer": "Blizzard",
      "price": 19.95
    }
  },
  "expensive": 10
}`

**Comment by luisfilsilva** [comment]
My fault.. found the issue.. was missing settings the Response strategy

**Comment by karldahlgren** [comment]
I'm glad you found the issue @luisfilsilva 😊
