### ISSUE TITLE
Multiple Input XPath Expressions

### ISSUE THREAD

**Issue by milkotodorov** [castlemock/castlemock#67]
Is it possible to combine several XPath expressions? When not - it would be a nice feature to be added.

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
Sure, I can add this to the next release. Could you give a suggestion on how you would like this to work?

Thanks!
Best regards,
Karl Dahlgren

**Comment by milkotodorov** [comment]
Hi @karldahlgren,

Thanks for you fast response and willingness to add this.
I would suggest that you make it like the Headers below. So you can add/delete a XPath Expression. And also to be a bit wider in oder to read the longer XPath rules easily.

Thank you!

**Comment by karldahlgren** [comment]
This issue has been implemented and will be part of the next release.

**Comment by milkotodorov** [comment]
That's looks great - thanks a lot!
