### ISSUE TITLE
WSDL with dependencies are not supported

### ISSUE THREAD

**Issue by milkotodorov** [castlemock/castlemock#68]
WDSLs that import another WSDLs cannot be imported properly.

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
Castle Mock tries to avoid dependencies when importing WSDLs, such as schemas and other WSDL files (Mainly since it is not always certain that Castle Mock have access to the linked dependencies). However, it would be interesting to investigate this. Could you provide an example on a WSDL that imports another WSDL file?

Thanks!
Best regards,
Karl Dahlgren

**Comment by milkotodorov** [comment]
Hi @karldahlgren,

here is one example: [wsdl_sample.zip](https://github.com/castlemock/castlemock/files/2261747/wsdl_sample.zip)

**Comment by milkotodorov** [comment]
Hi @karldahlgren,

do you have any estimations when this will be available?

Thank you!
Milko

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
It's hard to say, but I'm hoping to do some work on this during the weekend. This is on the top of my priority. I just returned back from traveling and intend to start working on this as soon as I can.

I will keep you posted :)

Thanks!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
This feature is almost done. However, it will only import WSDL files and mock them. It won't change the URL towards the linked WSDLs or anything like this. Would this work for you? Otherwise, it might take a little bit longer time.

Thanks!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
This issue has been implemented and will be part of the next release.

**Comment by milkotodorov** [comment]
Thanks @karldahlgren!
This should work I think. I'll give it a try.

**Comment by milkotodorov** [comment]
Hi @karldahlgren,

unfortunately this doesn't work. Have you tried to import the sample that I uploaded here?
Can you please check this further?

Thanks,
Milko
