### ISSUE TITLE
Building and running from maven without installed tomcat

### ISSUE THREAD

**Issue by tgkprog** [castlemock/castlemock#685]
**Is your feature request related to a problem? Please describe.**
My company blocks most downloads. Not able to download tomcat unless i get an exception. 

**Describe the solution you'd like**
A way to build and run castle mock from the command line using Java 19+ and maven

**Describe alternatives you've considered**
Try to build myself but not sure of dependancies and steps

**Additional context**
In the notes can specify what programs like Java 19, we should already have set up and no need to document how to do that. Just steps like:
1. Software needed : Java 19, Maven 3 ...
2.  clone repo, give these commands ... for linux, we can adapt for Windows (or give for Windows if you use that)

**Comment by mkysoft** [comment]
You needs a lot of libraries to compile it. You need internet connection for maven repositories. It has also React Web UI and it will download hundreds of node modules. Maybe you can create github actions to compile jar file in your own fork then use this jar file.

**Comment by tgkprog** [comment]
Thanks can close this
