### ISSUE TITLE
REST API response with status code 201

### ISSUE THREAD

**Issue by agulea** [castlemock/castlemock#69]
Hello,

I have a POST request that responds with status 201 in case of success. Do you know the response is not recorded in castle mock?
You can see it in the attached file. Thanks.
![image](https://user-images.githubusercontent.com/41696574/43702841-b51d19e6-9963-11e8-9bc2-a86de5125563.png)

Best regards,
AnaG

**Comment by karldahlgren** [comment]
Hi @agulea.
It is hard to say what could cause this problem. The returned response should always be logged. Can you reproduce the issue? Could you tell me a little bit more about your service? Was it configured to mock a response or was it configured to forward/record/record once/echo? 

Thank you very much!
Best regards,
Karl Dahlgren

**Comment by agulea** [comment]
Hi @karldahlgren ,

The method has two statuses:
- 200 in case of error and the response is a JSON
- 201 for success and the response is a JSON
Using castle mock a response is recorded only when I get a 200 status but not for 201. The service was configured to record.
I attached tow snapshot from rest/event stored files.
![post_without_response_logged](https://user-images.githubusercontent.com/41696574/43727792-a3d1ff6a-99ab-11e8-9a36-b27bfc02c03f.PNG)
![post_with_response_logged](https://user-images.githubusercontent.com/41696574/43727793-a3ed3352-99ab-11e8-876e-6bf30a836397.PNG)


Thank you very much!
Best regards,
AnaG

**Comment by karldahlgren** [comment]
Hi @agulea.
Sorry for the delayed response. I'm currently out traveling.
Thank you for the details! I'm currently looking into this. Don't really know what could cause this issue, but I will keep you posted.

Thanks again!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @agulea.
I haven't been able to reproduce this issue. Is this still causing issues for you?

Thanks!
Best regards,
Karl Dahlgren
