### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by timonych** [castlemock/castlemock#70]
Hello again, karldahlgren!

I have pushed a perf test on out web-service which is going to mock service.

After midnight the Mock service has taken the all CPU, but I can't understand why.

The SOAPMOCK has 4 CPU and 2 GB RAM. Maybe it needs more?

Do You have any ideas about it?
![2018-08-23 09_01_23-grafana - wls host soap](https://user-images.githubusercontent.com/2186304/44507453-4f06c280-a6b3-11e8-82e4-d697845f4a93.png)

**Comment by karldahlgren** [comment]
Hi @timonych.
Hmm, that is very odd. You shouldn't need any more memory or CPU. It should work fine. Did it go back to normal after a while or did you have to reboot the server? Did you know if you forward any requests? I was thinking if there was a service that might forward a request towards itself.

Is it repeatable or did it only happen once?

Once again, thank you very much for raising these issues. Very much appreciated.

Best regards,
Karl Dahlgren

**Comment by timonych** [comment]
Hi @karldahlgren 

I have started the PERF test at 17 by Moscow Time and You can it view on the Screen, that the the load start after 16 and the Utilization has been normal until 00:20.

When I stopped the testing the Utilization became normal, so the reboot of tomcat or server was not neccessary.

It happen once, but I haven't tested on such long period before. After vacation I will test it again.

**Comment by karldahlgren** [comment]
Hi @timonych.
I will keep an eye on this as well. 
Looking forward to hear how the tests goes.

Enjoy your vacation!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Unfortunately, I have been able to reproduce this issue. I will close it and re-open it if it occurs again. Thank you for understanding.

Best regards,
Karl Dahlgren
