### ISSUE TITLE
WSDL with dependencies not working

### ISSUE THREAD

**Issue by milkotodorov** [castlemock/castlemock#74]
Hello,

I just want to reopen issue https://github.com/castlemock/castlemock/issues/68 as the provided implementation doesn't work. I already replied there, but still do not get any reply...

Regards,
Milko

**Comment by milkotodorov** [comment]
Hi @karldahlgren,

all the .XSD and .WSDL files are referenced locally - not via link. Have a look inside the WSDL files.
The question is when I upload the w1.wsdl which points to another w2.wsdl and so on - are they all uploaded and available for castlemock? Or do you upload w1.wsdl without its dependencies?

By the way on which e-mail I can contact you? It's about contribution to your project...

Regards,
Milko

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
Ah, I see. In that case it won't work. I believe that the better solution there is to simply select multiple WSDL files to upload. That should do the trick for you :).

Regarding contribution: Contribution is always appreciated. Please send me an email to karl.dahlgren@castlemock.com and we can continue the conversation there.

Best regards,
Karl Dahlgren
