### ISSUE TITLE
XPath expression parsing

### ISSUE THREAD

**Issue by milkotodorov** [castlemock/castlemock#75]
Hello,

writing xpath expression cannot be parsed for the following XML:

```
   <soapenv:Body>
      <gps:getProduct>
         <productCode>INFORME_COMERCIAL</productCode>
         <productVersion>1.2</productVersion>
         <parameters>
            <parameter name="CIF">B63212930</parameter>
            <parameter name="NORMALIZADO">1</parameter>
            <parameter name="FORMATO_PGC">1</parameter>
            <parameter name="LITERALES">1</parameter>
            <parameter name="IDIOMA">03</parameter>
            <parameter name="REFERENCIA">test</parameter>
         </parameters>
      </gps:getProduct>
   </soapenv:Body>
```

I want to map the "CIF" parameter with the expression: `//getProduct/parameters/'parameter name=\"CIF\"'[text()='B63212930']`.

How the right syntax should be?

Thanks

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
The following syntax should work: 
> //getProduct/parameters/parameter[@name='CIF'][text()='B63212930']

I hope it helps. I will add a unit tests for this scenario as well.
Best regards,
Karl Dahlgren
