### ISSUE TITLE
Header deletion bug

### ISSUE THREAD

**Issue by milkotodorov** [castlemock/castlemock#78]
Hello All,

one more little bug - when you try to delete a header which is not the last one, it is deleted, but after one update the response and opens it again it stays like this:

![image](https://user-images.githubusercontent.com/14890886/45867139-09f1b100-bd83-11e8-90cc-cfaff5e7d107.png)

Thanks!

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
My apologies for the late response.
Thank you for raising this issue. This issue has already been resolved and will be part of the next release.

Best regards,
Karl Dahlgren
