### ISSUE TITLE
Support for permanent links

### ISSUE THREAD

**Issue by php-coder** [castlemock/castlemock#80]
The address of a mocked service contains a piece of random information that makes it unpredictable and hence hard to automate. For example, the URL http://172.22.0.4:8080/castlemock/mock/soap/project/fqIyhv/ServicesSOAPBinding contains `fqIyhv` that differs across projects.

It means if I put it to the application configuration, it won't work on a machine of my teammate.

One of the possible ways to solve this, is to introduce permanent links or aliases that can be specified during project creation.

Another way could be is to include a project name instead of this random bit of information.

**Comment by karldahlgren** [comment]
Hi @php-coder.
I like this idea. However, I would like to refer to my previous answer in issue 79. How are tried to export and import the project instead of reimporting the WSDL? That being said, I can definitely see being implemented in the future. 

Thanks!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @php-coder.
Did you see my previous answer? Did you manage to resolve this issue?

Best regards,
Karl Dahlgren

**Comment by avrezvanov** [comment]
Hello!
Did you manage to solve the issue with permanent links.
Due to dynamic symbols in the URL, I can't apply the teamwork solution.
