### ISSUE TITLE
Unable to identify SOAP operation Error Message

### ISSUE THREAD

**Issue by hallmont** [castlemock/castlemock#81]
Hi, I'm getting the following error when I try to call a SOAP mock service :

`<error-response>
    <error-message>Unable to identify SOAP operation: TempConvertSoap</error-message>
</error-response>`

I'm using the following WSDL :

https://github.com/marcosfjr/ControleTemperaturaDESKTOP/blob/master/xml-resources/web-service-references/tempconvert/wsdl/www.w3schools.com/webservices/tempconvert.asmx.wsdl

I use Postman to call it with the following URL :

http://localhost:8080/castlemock/mock/soap/project/Oqg1aQ/TempConvertSoap

Here's the body :

`<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CelsiusToFahrenheit xmlns="http://localhost:8080/castlemock/mock/soap/project/Oqg1aQ/TempConvertSoap">
      <Celsius>50</Celsius>
    </CelsiusToFahrenheit>
  </soap:Body>
</soap:Envelope>`

It may just be the case that not calling it properly.  Can you take a look to see if I'm using the right URL and body ?  I'm basically just trying to call the CelsiusToFahrenheit operation.

Thanks,

-- John

**Comment by karldahlgren** [comment]
Hi @hallmont.
It looks like the SOAP body that you are using is incorrect. Could you please try the following body instead?

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.w3schools.com/webservices/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:CelsiusToFahrenheit>
         <web:Celsius>?</web:Celsius>
      </web:CelsiusToFahrenheit>
   </soapenv:Body>
</soapenv:Envelope>`

Thank you!
Best regards,
Karl Dahlgren

**Comment by hallmont** [comment]
Thanks for the super fast response!  Yes, that works perfectly.  Thanks! -- John

**Comment by karldahlgren** [comment]
Great to hear!
Don't hesitate to contact me again if you need further support.

Best regards,
Karl Dahlgren
