### ISSUE TITLE
soap address location replace_with_actual_url

### ISSUE THREAD

**Issue by ishanrakitha** [castlemock/castlemock#88]
Everything works when executed from SOAP UI. I'm using apache cfx in my code base, when i execute from the program soap address location replace_with_actual_url.

Your feedback is highly appreciated.

**Comment by karldahlgren** [comment]
Hi @ishanrakitha.
I'm guessing that your code base is retrieving the WSDL file from Castle Mock and tries to send requests? Castle Mock does not modify the provided WSDL file and replace the old endpoint specified. 

Is it possible for you to specify the Castle Mock endpoint in your code base?

Thanks.
Best regards.
Karl Dahlgren

**Comment by ishanrakitha** [comment]
Hi @karldahlgren.

Codebase is already pointed to the Castle Mock endpoint. I'm using Apache CFX. When switched to SOAP UI Mock service it works. That means soap ui modifies the location to localhost ?

Thanks & Regards,
Ishan.

**Comment by karldahlgren** [comment]
So you are using Apache CXF to build web service or to consume the web services? Would it be possible for you to send me your WSDL file? You can send it to me directly on the following mail address: karl.dahlgren@castlemock.com

Thanks!
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Great to hear! Good luck with your project. 
Feel free to contact me again if you face any other issues.

Best regards,
Karl Dahlgren

**Comment by ishanrakitha** [comment]
Thank you so much and wish you the same! :)
